import * as THREE from 'three';
import { CHARACTER_CONFIG } from '../../character/character-config';

// Generated by scripts/quarks-to-native.mjs
// Source: subEmitter2.json
// DO NOT EDIT — re-run the converter to regenerate.

// ─── Bezier/curve helpers ────────────────────────────────────────────────────

function bezier3(p0: number, p1: number, p2: number, p3: number, t: number): number {
  const u = 1 - t; return u*u*u*p0 + 3*u*u*t*p1 + 3*u*t*t*p2 + t*t*t*p3;
}

interface PiecewiseCurve { start: number; end: number; p0: number; p1: number; p2: number; p3: number; }

function evalPiecewise(curves: PiecewiseCurve[], t: number): number {
  if (curves.length === 0) return 0;
  for (let i = 0; i < curves.length; i++) {
    const c = curves[i];
    if (t >= c.start && t <= c.end) {
      const nt = (c.end === c.start) ? 0 : (t - c.start) / (c.end - c.start);
      return bezier3(c.p0, c.p1, c.p2, c.p3, nt);
    }
  }
  if (t < curves[0].start) return bezier3(curves[0].p0, curves[0].p1, curves[0].p2, curves[0].p3, 0);
  const last = curves[curves.length - 1];
  return bezier3(last.p0, last.p1, last.p2, last.p3, 1.0);
}

interface ColorKey { value: { r: number; g: number; b: number }; pos: number; }
interface AlphaKey { value: number; pos: number; }

function evalAlpha(keys: AlphaKey[], t: number): number {
  for (let i = 0; i < keys.length - 1; i++) {
    if (t <= keys[i+1].pos) {
      const lt = (t - keys[i].pos) / (keys[i+1].pos - keys[i].pos);
      return keys[i].value + lt * (keys[i+1].value - keys[i].value);
    }
  }
  return keys[keys.length-1].value;
}

function evalColor(keys: ColorKey[], t: number) {
  for (let i = 0; i < keys.length - 1; i++) {
    if (t <= keys[i+1].pos) {
      const lt = (t - keys[i].pos) / (keys[i+1].pos - keys[i].pos);
      return {
        r: keys[i].value.r + lt * (keys[i+1].value.r - keys[i].value.r),
        g: keys[i].value.g + lt * (keys[i+1].value.g - keys[i].value.g),
        b: keys[i].value.b + lt * (keys[i+1].value.b - keys[i].value.b),
      };
    }
  }
  return keys[keys.length-1].value;
}

function rng(a: number, b: number) { return a + Math.random() * (b - a); }

// ─── VFX Class ───────────────────────────────────────────────────────────────

export class Subemitter2NativeVFX {
  private scene: THREE.Scene;
  private camera: THREE.Camera;
  private activeFX: Array<{ update: (delta: number) => boolean }> = [];
  private tex0: THREE.Texture;
  private tex1: THREE.Texture;
  private tex2: THREE.Texture;
  private tex3: THREE.Texture;

  constructor(scene: THREE.Scene, camera: THREE.Camera) {
    this.scene = scene;
    this.camera = camera;
    const L = new THREE.TextureLoader();
    this.tex0 = L.load('/vfx/subemitter2/tex_0.png');
    this.tex1 = L.load('/vfx/subemitter2/tex_1.png');
    this.tex2 = L.load('/vfx/subemitter2/tex_2.png');
    this.tex3 = L.load('/vfx/subemitter2/tex_3.png');
  }

  public spawn(x: number, y: number, z: number) {
    const origin = new THREE.Vector3(x, y, z);
    const T = new THREE.Object3D();
    const hideM = new THREE.Matrix4().makeScale(0, 0, 0);
    const cq = this.camera.quaternion;
    const cfgColor = new THREE.Color(CHARACTER_CONFIG.skills.gasExplosion.hudColor);
    let age = 0;
    const cleanups: (() => void)[] = [];

    // ══════════════════════════════════════════════════════════
    // Emitter: SmokeCloudsUpEmitter  (count=40, life=[0.6, 2], speed=[2, 55])
    // Texture: tex_0.png  Grid: 2x2
    // ══════════════════════════════════════════════════════════
    const cnt_SmokeCloudsUpEmitter = 40;
    const geo_SmokeCloudsUpEmitter = new THREE.PlaneGeometry(1, 1);
    const mat_SmokeCloudsUpEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex0 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          float c = mod(aFrame, 2.0); float r = floor(aFrame / 2.0);
          vUv = vec2((c + uv.x) / 2.0, 1.0 - (r + 1.0 - uv.y) / 2.0);
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_SmokeCloudsUpEmitter = new THREE.InstancedMesh(geo_SmokeCloudsUpEmitter, mat_SmokeCloudsUpEmitter, cnt_SmokeCloudsUpEmitter);
    mesh_SmokeCloudsUpEmitter.frustumCulled = false;
    this.scene.add(mesh_SmokeCloudsUpEmitter);
    const frm_SmokeCloudsUpEmitter = new Float32Array(cnt_SmokeCloudsUpEmitter);
    const opc_SmokeCloudsUpEmitter = new Float32Array(cnt_SmokeCloudsUpEmitter);
    const clr_SmokeCloudsUpEmitter = new Float32Array(cnt_SmokeCloudsUpEmitter * 3);
    mesh_SmokeCloudsUpEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_SmokeCloudsUpEmitter, 1));
    mesh_SmokeCloudsUpEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_SmokeCloudsUpEmitter, 1));
    mesh_SmokeCloudsUpEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_SmokeCloudsUpEmitter, 3));

    const life_SmokeCloudsUpEmitter: number[] = [];
    const maxLife_SmokeCloudsUpEmitter: number[] = [];
    const pos_SmokeCloudsUpEmitter: THREE.Vector3[] = [];
    const vel_SmokeCloudsUpEmitter: THREE.Vector3[] = [];
    const sz_SmokeCloudsUpEmitter: number[] = [];
    const rot_SmokeCloudsUpEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_SmokeCloudsUpEmitter; i++) {
      life_SmokeCloudsUpEmitter.push(1.0);
      maxLife_SmokeCloudsUpEmitter.push(1.0);
      pos_SmokeCloudsUpEmitter.push(new THREE.Vector3(x, y, z));
      vel_SmokeCloudsUpEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_SmokeCloudsUpEmitter.push(0);
      rot_SmokeCloudsUpEmitter.push(0);
      
    }

    let ptr_SmokeCloudsUpEmitter = 0;
    let spawnTimer_SmokeCloudsUpEmitter = 0;

    const spawnParticle_SmokeCloudsUpEmitter = (i: number) => {
      life_SmokeCloudsUpEmitter[i] = 0;
      maxLife_SmokeCloudsUpEmitter[i] = rng(0.6, 2);
      sz_SmokeCloudsUpEmitter[i] = rng(1.4, 1.7);
      rot_SmokeCloudsUpEmitter[i] = rng(0, Math.PI * 2);
      
      const u = Math.random();
      const rand = Math.random();
      const theta = u * 6.283185307179586;
      const r = Math.sqrt(rand);
      const sinTheta = Math.sin(theta);
      const cosTheta = Math.cos(theta);
      const pX = r * cosTheta;
      const pY = r * sinTheta;
      
      const angle = 0.19198621771937624 * r;
      const speed = rng(2, 55) * 2.0;
      const srad = 0.2 * 2.0;
      
      pos_SmokeCloudsUpEmitter[i].set(
        x + pX * srad,
        y,
        z + pY * srad
      );
      vel_SmokeCloudsUpEmitter[i].set(
        pX * Math.sin(angle) * speed,
        Math.cos(angle) * speed,
        pY * Math.sin(angle) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_SmokeCloudsUpEmitter = 30;
    for (let i = 0; i < Math.min(cnt_SmokeCloudsUpEmitter, initialBurst_SmokeCloudsUpEmitter); i++) {
      spawnParticle_SmokeCloudsUpEmitter(ptr_SmokeCloudsUpEmitter);
      ptr_SmokeCloudsUpEmitter = (ptr_SmokeCloudsUpEmitter + 1) % cnt_SmokeCloudsUpEmitter;
    }
  
    const colorKeys_SmokeCloudsUpEmitter: ColorKey[] | null = [{ value: { r: 0.00000, g: 0.62745, b: 1.00000 }, pos: 0.00000 }, { value: { r: 0.24373, g: 0.27175, b: 0.33824 }, pos: 0.35830 }];
    const alphaKeys_SmokeCloudsUpEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00000 }, { value: 1.00000, pos: 0.90001 }, { value: 0.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_SmokeCloudsUpEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_SmokeCloudsUpEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_SmokeCloudsUpEmitter >= interval) {
          spawnParticle_SmokeCloudsUpEmitter(ptr_SmokeCloudsUpEmitter);
          ptr_SmokeCloudsUpEmitter = (ptr_SmokeCloudsUpEmitter + 1) % cnt_SmokeCloudsUpEmitter;
          spawnTimer_SmokeCloudsUpEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_SmokeCloudsUpEmitter; i++) {
        if (life_SmokeCloudsUpEmitter[i] >= maxLife_SmokeCloudsUpEmitter[i]) {
          mesh_SmokeCloudsUpEmitter.setMatrixAt(i, hideM);
          opc_SmokeCloudsUpEmitter[i] = 0;
          continue;
        }
        life_SmokeCloudsUpEmitter[i] += dt;
        const pct = Math.min(1, life_SmokeCloudsUpEmitter[i] / maxLife_SmokeCloudsUpEmitter[i]);
        if (life_SmokeCloudsUpEmitter[i] >= maxLife_SmokeCloudsUpEmitter[i]) {
          mesh_SmokeCloudsUpEmitter.setMatrixAt(i, hideM);
          opc_SmokeCloudsUpEmitter[i] = 0;
          continue;
        }
        // Physics: gravity + drag
        vel_SmokeCloudsUpEmitter[i].y += 4.9 * dt;
        
        const speed_SmokeCloudsUpEmitter = vel_SmokeCloudsUpEmitter[i].length();
        const limit_SmokeCloudsUpEmitter = 1 * 2.0;
        if (speed_SmokeCloudsUpEmitter > limit_SmokeCloudsUpEmitter) {
          const percent = (speed_SmokeCloudsUpEmitter - limit_SmokeCloudsUpEmitter) / speed_SmokeCloudsUpEmitter;
          vel_SmokeCloudsUpEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.3 * dt * 20));
        }
    
        pos_SmokeCloudsUpEmitter[i].addScaledVector(vel_SmokeCloudsUpEmitter[i], dt);
        
        const rotSpeedBez_SmokeCloudsUpEmitter: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0, p3: 0}];
        rot_SmokeCloudsUpEmitter[i] += evalPiecewise(rotSpeedBez_SmokeCloudsUpEmitter, pct) * dt;
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 0.21149425, p0: 1, p1: 1, p2: 1, p3: 1}, {start: 0.21149425, end: 1, p0: 1, p1: 1, p2: 0.5256705, p3: 0}];
        const scaledSz = sz_SmokeCloudsUpEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_SmokeCloudsUpEmitter ? evalAlpha(alphaKeys_SmokeCloudsUpEmitter, pct) : (1 - pct);
        const col = colorKeys_SmokeCloudsUpEmitter ? evalColor(colorKeys_SmokeCloudsUpEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_SmokeCloudsUpEmitter[i]);
        
        T.quaternion.copy(cq);
        T.rotateZ(rot_SmokeCloudsUpEmitter[i]);
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_SmokeCloudsUpEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [{start: 0, end: 1.0, p0: 0, p1: 0, p2: 3.9996, p3: 3.9996}];
        const frameRaw = evalPiecewise(frameBez, pct);
        frm_SmokeCloudsUpEmitter[i] = Math.min(3, Math.floor(frameRaw));
        opc_SmokeCloudsUpEmitter[i] = alpha;
        clr_SmokeCloudsUpEmitter[i*3+0] = col.r * cfgColor.r; clr_SmokeCloudsUpEmitter[i*3+1] = col.g * cfgColor.g; clr_SmokeCloudsUpEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_SmokeCloudsUpEmitter.instanceMatrix.needsUpdate = true;
      (mesh_SmokeCloudsUpEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SmokeCloudsUpEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SmokeCloudsUpEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_SmokeCloudsUpEmitter);
      geo_SmokeCloudsUpEmitter.dispose(); mat_SmokeCloudsUpEmitter.dispose();
      (mesh_SmokeCloudsUpEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: SmokeCloudsEmitter  (count=30, life=[0.6, 2], speed=[9, 12])
    // Texture: tex_0.png  Grid: 2x2
    // ══════════════════════════════════════════════════════════
    const cnt_SmokeCloudsEmitter = 30;
    const geo_SmokeCloudsEmitter = new THREE.PlaneGeometry(1, 1);
    const mat_SmokeCloudsEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex0 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          float c = mod(aFrame, 2.0); float r = floor(aFrame / 2.0);
          vUv = vec2((c + uv.x) / 2.0, 1.0 - (r + 1.0 - uv.y) / 2.0);
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_SmokeCloudsEmitter = new THREE.InstancedMesh(geo_SmokeCloudsEmitter, mat_SmokeCloudsEmitter, cnt_SmokeCloudsEmitter);
    mesh_SmokeCloudsEmitter.frustumCulled = false;
    this.scene.add(mesh_SmokeCloudsEmitter);
    const frm_SmokeCloudsEmitter = new Float32Array(cnt_SmokeCloudsEmitter);
    const opc_SmokeCloudsEmitter = new Float32Array(cnt_SmokeCloudsEmitter);
    const clr_SmokeCloudsEmitter = new Float32Array(cnt_SmokeCloudsEmitter * 3);
    mesh_SmokeCloudsEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_SmokeCloudsEmitter, 1));
    mesh_SmokeCloudsEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_SmokeCloudsEmitter, 1));
    mesh_SmokeCloudsEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_SmokeCloudsEmitter, 3));

    const life_SmokeCloudsEmitter: number[] = [];
    const maxLife_SmokeCloudsEmitter: number[] = [];
    const pos_SmokeCloudsEmitter: THREE.Vector3[] = [];
    const vel_SmokeCloudsEmitter: THREE.Vector3[] = [];
    const sz_SmokeCloudsEmitter: number[] = [];
    const rot_SmokeCloudsEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_SmokeCloudsEmitter; i++) {
      life_SmokeCloudsEmitter.push(1.0);
      maxLife_SmokeCloudsEmitter.push(1.0);
      pos_SmokeCloudsEmitter.push(new THREE.Vector3(x, y, z));
      vel_SmokeCloudsEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_SmokeCloudsEmitter.push(0);
      rot_SmokeCloudsEmitter.push(0);
      
    }

    let ptr_SmokeCloudsEmitter = 0;
    let spawnTimer_SmokeCloudsEmitter = 0;

    const spawnParticle_SmokeCloudsEmitter = (i: number) => {
      life_SmokeCloudsEmitter[i] = 0;
      maxLife_SmokeCloudsEmitter[i] = rng(0.6, 2);
      sz_SmokeCloudsEmitter[i] = rng(0.99999994, 1.7);
      rot_SmokeCloudsEmitter[i] = rng(0, Math.PI * 2);
      
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(rng(-1, 1));
      const speed = rng(9, 12) * 2.0;
      const srad = 0.4 * 2.0;
      pos_SmokeCloudsEmitter[i].set(
        x + Math.sin(phi) * Math.cos(theta) * srad,
        y + Math.cos(phi) * srad,
        z + Math.sin(phi) * Math.sin(theta) * srad
      );
      vel_SmokeCloudsEmitter[i].set(
        Math.sin(phi) * Math.cos(theta) * speed,
        Math.cos(phi) * speed,
        Math.sin(phi) * Math.sin(theta) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_SmokeCloudsEmitter = 20;
    for (let i = 0; i < Math.min(cnt_SmokeCloudsEmitter, initialBurst_SmokeCloudsEmitter); i++) {
      spawnParticle_SmokeCloudsEmitter(ptr_SmokeCloudsEmitter);
      ptr_SmokeCloudsEmitter = (ptr_SmokeCloudsEmitter + 1) % cnt_SmokeCloudsEmitter;
    }
  
    const colorKeys_SmokeCloudsEmitter: ColorKey[] | null = [{ value: { r: 0.00000, g: 0.62745, b: 1.00000 }, pos: 0.00000 }, { value: { r: 0.24373, g: 0.27175, b: 0.33824 }, pos: 0.35830 }];
    const alphaKeys_SmokeCloudsEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00000 }, { value: 1.00000, pos: 0.90001 }, { value: 0.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_SmokeCloudsEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_SmokeCloudsEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_SmokeCloudsEmitter >= interval) {
          spawnParticle_SmokeCloudsEmitter(ptr_SmokeCloudsEmitter);
          ptr_SmokeCloudsEmitter = (ptr_SmokeCloudsEmitter + 1) % cnt_SmokeCloudsEmitter;
          spawnTimer_SmokeCloudsEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_SmokeCloudsEmitter; i++) {
        if (life_SmokeCloudsEmitter[i] >= maxLife_SmokeCloudsEmitter[i]) {
          mesh_SmokeCloudsEmitter.setMatrixAt(i, hideM);
          opc_SmokeCloudsEmitter[i] = 0;
          continue;
        }
        life_SmokeCloudsEmitter[i] += dt;
        const pct = Math.min(1, life_SmokeCloudsEmitter[i] / maxLife_SmokeCloudsEmitter[i]);
        if (life_SmokeCloudsEmitter[i] >= maxLife_SmokeCloudsEmitter[i]) {
          mesh_SmokeCloudsEmitter.setMatrixAt(i, hideM);
          opc_SmokeCloudsEmitter[i] = 0;
          continue;
        }
        // Physics: gravity + drag
        vel_SmokeCloudsEmitter[i].y += 4.9 * dt;
        
        const speed_SmokeCloudsEmitter = vel_SmokeCloudsEmitter[i].length();
        const limit_SmokeCloudsEmitter = 0.5 * 2.0;
        if (speed_SmokeCloudsEmitter > limit_SmokeCloudsEmitter) {
          const percent = (speed_SmokeCloudsEmitter - limit_SmokeCloudsEmitter) / speed_SmokeCloudsEmitter;
          vel_SmokeCloudsEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.15 * dt * 20));
        }
    
        pos_SmokeCloudsEmitter[i].addScaledVector(vel_SmokeCloudsEmitter[i], dt);
        
        const rotSpeedBez_SmokeCloudsEmitter: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0, p3: 0}];
        rot_SmokeCloudsEmitter[i] += evalPiecewise(rotSpeedBez_SmokeCloudsEmitter, pct) * dt;
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 0.21149425, p0: 1, p1: 1, p2: 1, p3: 1}, {start: 0.21149425, end: 1, p0: 1, p1: 1, p2: 0.5256705, p3: 0}];
        const scaledSz = sz_SmokeCloudsEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_SmokeCloudsEmitter ? evalAlpha(alphaKeys_SmokeCloudsEmitter, pct) : (1 - pct);
        const col = colorKeys_SmokeCloudsEmitter ? evalColor(colorKeys_SmokeCloudsEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_SmokeCloudsEmitter[i]);
        
        T.quaternion.copy(cq);
        T.rotateZ(rot_SmokeCloudsEmitter[i]);
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_SmokeCloudsEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [{start: 0, end: 1.0, p0: 0, p1: 0, p2: 3.9996, p3: 3.9996}];
        const frameRaw = evalPiecewise(frameBez, pct);
        frm_SmokeCloudsEmitter[i] = Math.min(3, Math.floor(frameRaw));
        opc_SmokeCloudsEmitter[i] = alpha;
        clr_SmokeCloudsEmitter[i*3+0] = col.r * cfgColor.r; clr_SmokeCloudsEmitter[i*3+1] = col.g * cfgColor.g; clr_SmokeCloudsEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_SmokeCloudsEmitter.instanceMatrix.needsUpdate = true;
      (mesh_SmokeCloudsEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SmokeCloudsEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SmokeCloudsEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_SmokeCloudsEmitter);
      geo_SmokeCloudsEmitter.dispose(); mat_SmokeCloudsEmitter.dispose();
      (mesh_SmokeCloudsEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: SparksEmitter  (count=35, life=[0.25, 1.2], speed=[11, 31])
    // Texture: tex_1.png  Grid: 1x1
    // ══════════════════════════════════════════════════════════
    const cnt_SparksEmitter = 35;
    const geo_SparksEmitter = new THREE.PlaneGeometry(1, 1);
    const mat_SparksEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex1 }, speedFactor: { value: 0.0100 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor; attribute vec3 aVelocity; attribute vec3 aOffset;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        uniform float speedFactor;
        void main() {
          float c = mod(aFrame, 1.0); float r = floor(aFrame / 1.0);
          vUv = vec2((c + uv.x) / 1.0, 1.0 - (r + 1.0 - uv.y) / 1.0);
          vOpacity = aOpacity; vColor = aColor;
          vec4 mvPos = modelViewMatrix * vec4(aOffset, 1.0);
          vec3 viewVel = normalMatrix * aVelocity;
          float vlength = length(viewVel);
          float avgSize = (instanceMatrix[0][0] + instanceMatrix[1][1]) * 0.5;
          float sz = length(vec3(instanceMatrix[0][0], instanceMatrix[0][1], instanceMatrix[0][2]));
          mvPos.xyz += position.y * normalize(cross(mvPos.xyz, viewVel)) * sz;
          mvPos.xyz -= (position.x + 0.5) * viewVel * (1.0 + 1.0000 / max(vlength, 0.001)) * sz;
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * mvPos;
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.NormalBlending
    });
    const mesh_SparksEmitter = new THREE.InstancedMesh(geo_SparksEmitter, mat_SparksEmitter, cnt_SparksEmitter);
    mesh_SparksEmitter.frustumCulled = false;
    this.scene.add(mesh_SparksEmitter);
    const frm_SparksEmitter = new Float32Array(cnt_SparksEmitter);
    const opc_SparksEmitter = new Float32Array(cnt_SparksEmitter);
    const clr_SparksEmitter = new Float32Array(cnt_SparksEmitter * 3);
    mesh_SparksEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_SparksEmitter, 1));
    mesh_SparksEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_SparksEmitter, 1));
    mesh_SparksEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_SparksEmitter, 3));
    const vel_buf_SparksEmitter = new Float32Array(cnt_SparksEmitter * 3);
    const off_buf_SparksEmitter = new Float32Array(cnt_SparksEmitter * 3);
    mesh_SparksEmitter.geometry.setAttribute('aVelocity', new THREE.InstancedBufferAttribute(vel_buf_SparksEmitter, 3));
    mesh_SparksEmitter.geometry.setAttribute('aOffset', new THREE.InstancedBufferAttribute(off_buf_SparksEmitter, 3));

    const life_SparksEmitter: number[] = [];
    const maxLife_SparksEmitter: number[] = [];
    const pos_SparksEmitter: THREE.Vector3[] = [];
    const vel_SparksEmitter: THREE.Vector3[] = [];
    const sz_SparksEmitter: number[] = [];
    const rot_SparksEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_SparksEmitter; i++) {
      life_SparksEmitter.push(1.0);
      maxLife_SparksEmitter.push(1.0);
      pos_SparksEmitter.push(new THREE.Vector3(x, y, z));
      vel_SparksEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_SparksEmitter.push(0);
      rot_SparksEmitter.push(0);
      
    }

    let ptr_SparksEmitter = 0;
    let spawnTimer_SparksEmitter = 0;

    const spawnParticle_SparksEmitter = (i: number) => {
      life_SparksEmitter[i] = 0;
      maxLife_SparksEmitter[i] = rng(0.25, 1.2);
      sz_SparksEmitter[i] = rng(0.08, 0.15);
      rot_SparksEmitter[i] = rng(0, Math.PI * 2);
      
      const u = Math.random();
      const rand = Math.random();
      const theta = u * 6.283185307179586;
      const r = Math.sqrt(rand);
      const sinTheta = Math.sin(theta);
      const cosTheta = Math.cos(theta);
      const pX = r * cosTheta;
      const pY = r * sinTheta;
      
      const angle = 0.7312929565856241 * r;
      const speed = rng(11, 31) * 2.0;
      const srad = 0.8 * 2.0;
      
      pos_SparksEmitter[i].set(
        x + pX * srad,
        y,
        z + pY * srad
      );
      vel_SparksEmitter[i].set(
        pX * Math.sin(angle) * speed,
        Math.cos(angle) * speed,
        pY * Math.sin(angle) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_SparksEmitter = 25;
    for (let i = 0; i < Math.min(cnt_SparksEmitter, initialBurst_SparksEmitter); i++) {
      spawnParticle_SparksEmitter(ptr_SparksEmitter);
      ptr_SparksEmitter = (ptr_SparksEmitter + 1) % cnt_SparksEmitter;
    }
  
    const colorKeys_SparksEmitter: ColorKey[] | null = [{ value: { r: 1.00000, g: 1.00000, b: 1.00000 }, pos: 0.00000 }, { value: { r: 0.00000, g: 0.83529, b: 1.00000 }, pos: 1.00000 }];
    const alphaKeys_SparksEmitter: AlphaKey[] | null = [{ value: 0.00000, pos: 0.00000 }, { value: 1.00000, pos: 0.09425 }, { value: 1.00000, pos: 0.83487 }, { value: 0.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_SparksEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_SparksEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_SparksEmitter >= interval) {
          spawnParticle_SparksEmitter(ptr_SparksEmitter);
          ptr_SparksEmitter = (ptr_SparksEmitter + 1) % cnt_SparksEmitter;
          spawnTimer_SparksEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_SparksEmitter; i++) {
        if (life_SparksEmitter[i] >= maxLife_SparksEmitter[i]) {
          mesh_SparksEmitter.setMatrixAt(i, hideM);
          opc_SparksEmitter[i] = 0;
          continue;
        }
        life_SparksEmitter[i] += dt;
        const pct = Math.min(1, life_SparksEmitter[i] / maxLife_SparksEmitter[i]);
        if (life_SparksEmitter[i] >= maxLife_SparksEmitter[i]) {
          mesh_SparksEmitter.setMatrixAt(i, hideM);
          opc_SparksEmitter[i] = 0;
          continue;
        }
        // Physics: gravity + drag
        vel_SparksEmitter[i].y += -19.6 * dt;
        
        const speed_SparksEmitter = vel_SparksEmitter[i].length();
        const limit_SparksEmitter = 0 * 2.0;
        if (speed_SparksEmitter > limit_SparksEmitter) {
          const percent = (speed_SparksEmitter - limit_SparksEmitter) / speed_SparksEmitter;
          vel_SparksEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.15 * dt * 20));
        }
    
        pos_SparksEmitter[i].addScaledVector(vel_SparksEmitter[i], dt);
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0.6666666666666666, p3: 0}];
        const scaledSz = sz_SparksEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_SparksEmitter ? evalAlpha(alphaKeys_SparksEmitter, pct) : (1 - pct);
        const col = colorKeys_SparksEmitter ? evalColor(colorKeys_SparksEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        // StretchedBillboard: shader handles orientation via aVelocity/aOffset
        T.scale.setScalar(scaledSz);
        off_buf_SparksEmitter[i*3+0] = pos_SparksEmitter[i].x;
        off_buf_SparksEmitter[i*3+1] = pos_SparksEmitter[i].y;
        off_buf_SparksEmitter[i*3+2] = pos_SparksEmitter[i].z;
        vel_buf_SparksEmitter[i*3+0] = vel_SparksEmitter[i].x * 0.0100;
        vel_buf_SparksEmitter[i*3+1] = vel_SparksEmitter[i].y * 0.0100;
        vel_buf_SparksEmitter[i*3+2] = vel_SparksEmitter[i].z * 0.0100;
        
        T.updateMatrix();
        mesh_SparksEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [];
        const frameRaw = pct * 1;
        frm_SparksEmitter[i] = Math.min(0, Math.floor(frameRaw));
        opc_SparksEmitter[i] = alpha;
        clr_SparksEmitter[i*3+0] = col.r * cfgColor.r; clr_SparksEmitter[i*3+1] = col.g * cfgColor.g; clr_SparksEmitter[i*3+2] = col.b * cfgColor.b;
        mesh_SparksEmitter.geometry.attributes.aVelocity.needsUpdate = true;
        mesh_SparksEmitter.geometry.attributes.aOffset.needsUpdate = true;
      }
      mesh_SparksEmitter.instanceMatrix.needsUpdate = true;
      (mesh_SparksEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SparksEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SparksEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_SparksEmitter);
      geo_SparksEmitter.dispose(); mat_SparksEmitter.dispose();
      (mesh_SparksEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: FireBallEmitter  (count=25, life=[0.15, 0.6], speed=[6.000001, 18])
    // Texture: tex_1.png  Grid: 1x1
    // ══════════════════════════════════════════════════════════
    const cnt_FireBallEmitter = 25;
    const geo_FireBallEmitter = new THREE.PlaneGeometry(1, 1);
    const mat_FireBallEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex1 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vUv = uv;
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_FireBallEmitter = new THREE.InstancedMesh(geo_FireBallEmitter, mat_FireBallEmitter, cnt_FireBallEmitter);
    mesh_FireBallEmitter.frustumCulled = false;
    this.scene.add(mesh_FireBallEmitter);
    const frm_FireBallEmitter = new Float32Array(cnt_FireBallEmitter);
    const opc_FireBallEmitter = new Float32Array(cnt_FireBallEmitter);
    const clr_FireBallEmitter = new Float32Array(cnt_FireBallEmitter * 3);
    mesh_FireBallEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_FireBallEmitter, 1));
    mesh_FireBallEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_FireBallEmitter, 1));
    mesh_FireBallEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_FireBallEmitter, 3));

    const life_FireBallEmitter: number[] = [];
    const maxLife_FireBallEmitter: number[] = [];
    const pos_FireBallEmitter: THREE.Vector3[] = [];
    const vel_FireBallEmitter: THREE.Vector3[] = [];
    const sz_FireBallEmitter: number[] = [];
    const rot_FireBallEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_FireBallEmitter; i++) {
      life_FireBallEmitter.push(1.0);
      maxLife_FireBallEmitter.push(1.0);
      pos_FireBallEmitter.push(new THREE.Vector3(x, y, z));
      vel_FireBallEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_FireBallEmitter.push(0);
      rot_FireBallEmitter.push(0);
      
    }

    let ptr_FireBallEmitter = 0;
    let spawnTimer_FireBallEmitter = 0;

    const spawnParticle_FireBallEmitter = (i: number) => {
      life_FireBallEmitter[i] = 0;
      maxLife_FireBallEmitter[i] = rng(0.15, 0.6);
      sz_FireBallEmitter[i] = rng(0.6, 1.3);
      rot_FireBallEmitter[i] = rng(0, Math.PI * 2);
      
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(rng(-1, 1));
      const speed = rng(6.000001, 18) * 2.0;
      const srad = 0.01 * 2.0;
      pos_FireBallEmitter[i].set(
        x + Math.sin(phi) * Math.cos(theta) * srad,
        y + Math.cos(phi) * srad,
        z + Math.sin(phi) * Math.sin(theta) * srad
      );
      vel_FireBallEmitter[i].set(
        Math.sin(phi) * Math.cos(theta) * speed,
        Math.cos(phi) * speed,
        Math.sin(phi) * Math.sin(theta) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_FireBallEmitter = 15;
    for (let i = 0; i < Math.min(cnt_FireBallEmitter, initialBurst_FireBallEmitter); i++) {
      spawnParticle_FireBallEmitter(ptr_FireBallEmitter);
      ptr_FireBallEmitter = (ptr_FireBallEmitter + 1) % cnt_FireBallEmitter;
    }
  
    const colorKeys_FireBallEmitter: ColorKey[] | null = [{ value: { r: 1.00000, g: 1.00000, b: 1.00000 }, pos: 0.30344 }, { value: { r: 0.00000, g: 1.00000, b: 1.00000 }, pos: 0.68276 }, { value: { r: 0.00000, g: 0.25490, b: 1.00000 }, pos: 1.00000 }];
    const alphaKeys_FireBallEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00000 }, { value: 1.00000, pos: 0.90001 }];

    // Update closure captured for this emitter
    const update_FireBallEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_FireBallEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_FireBallEmitter >= interval) {
          spawnParticle_FireBallEmitter(ptr_FireBallEmitter);
          ptr_FireBallEmitter = (ptr_FireBallEmitter + 1) % cnt_FireBallEmitter;
          spawnTimer_FireBallEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_FireBallEmitter; i++) {
        if (life_FireBallEmitter[i] >= maxLife_FireBallEmitter[i]) {
          mesh_FireBallEmitter.setMatrixAt(i, hideM);
          
          continue;
        }
        life_FireBallEmitter[i] += dt;
        const pct = Math.min(1, life_FireBallEmitter[i] / maxLife_FireBallEmitter[i]);
        if (life_FireBallEmitter[i] >= maxLife_FireBallEmitter[i]) {
          mesh_FireBallEmitter.setMatrixAt(i, hideM);
          
          continue;
        }
        // Physics: gravity + drag
        vel_FireBallEmitter[i].y += 0 * dt;
        
        const speed_FireBallEmitter = vel_FireBallEmitter[i].length();
        const limit_FireBallEmitter = 0 * 2.0;
        if (speed_FireBallEmitter > limit_FireBallEmitter) {
          const percent = (speed_FireBallEmitter - limit_FireBallEmitter) / speed_FireBallEmitter;
          vel_FireBallEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.25 * dt * 20));
        }
    
        pos_FireBallEmitter[i].addScaledVector(vel_FireBallEmitter[i], dt);
        
        const rotSpeedBez_FireBallEmitter: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0, p3: 0}];
        rot_FireBallEmitter[i] += evalPiecewise(rotSpeedBez_FireBallEmitter, pct) * dt;
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0.6666666666666666, p3: 0}];
        const scaledSz = sz_FireBallEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_FireBallEmitter ? evalAlpha(alphaKeys_FireBallEmitter, pct) : (1 - pct);
        const col = colorKeys_FireBallEmitter ? evalColor(colorKeys_FireBallEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_FireBallEmitter[i]);
        
        T.quaternion.copy(cq);
        T.rotateZ(rot_FireBallEmitter[i]);
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_FireBallEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [];
        const frameRaw = pct * 1;
        frm_FireBallEmitter[i] = Math.min(0, Math.floor(frameRaw));
        opc_FireBallEmitter[i] = alpha;
        clr_FireBallEmitter[i*3+0] = col.r * cfgColor.r; clr_FireBallEmitter[i*3+1] = col.g * cfgColor.g; clr_FireBallEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_FireBallEmitter.instanceMatrix.needsUpdate = true;
      (mesh_FireBallEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_FireBallEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_FireBallEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_FireBallEmitter);
      geo_FireBallEmitter.dispose(); mat_FireBallEmitter.dispose();
      (mesh_FireBallEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: SphereEmitter  (count=11, life=[0.5, 0.5], speed=[0, 0])
    // Texture: tex_-1.png  Grid: 1x1
    // ══════════════════════════════════════════════════════════
    const cnt_SphereEmitter = 11;
    const geo_SphereEmitter = new THREE.SphereGeometry(0.5, 16, 8);
    const mat_SphereEmitter = new THREE.ShaderMaterial({
      uniforms: {},
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vUv = uv;
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          gl_FragColor = vec4(vColor, vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_SphereEmitter = new THREE.InstancedMesh(geo_SphereEmitter, mat_SphereEmitter, cnt_SphereEmitter);
    mesh_SphereEmitter.frustumCulled = false;
    this.scene.add(mesh_SphereEmitter);
    const frm_SphereEmitter = new Float32Array(cnt_SphereEmitter);
    const opc_SphereEmitter = new Float32Array(cnt_SphereEmitter);
    const clr_SphereEmitter = new Float32Array(cnt_SphereEmitter * 3);
    mesh_SphereEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_SphereEmitter, 1));
    mesh_SphereEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_SphereEmitter, 1));
    mesh_SphereEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_SphereEmitter, 3));

    const life_SphereEmitter: number[] = [];
    const maxLife_SphereEmitter: number[] = [];
    const pos_SphereEmitter: THREE.Vector3[] = [];
    const vel_SphereEmitter: THREE.Vector3[] = [];
    const sz_SphereEmitter: number[] = [];
    const rot_SphereEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_SphereEmitter; i++) {
      life_SphereEmitter.push(1.0);
      maxLife_SphereEmitter.push(1.0);
      pos_SphereEmitter.push(new THREE.Vector3(x, y, z));
      vel_SphereEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_SphereEmitter.push(0);
      rot_SphereEmitter.push(0);
      
    }

    let ptr_SphereEmitter = 0;
    let spawnTimer_SphereEmitter = 0;

    const spawnParticle_SphereEmitter = (i: number) => {
      life_SphereEmitter[i] = 0;
      maxLife_SphereEmitter[i] = rng(0.5, 0.5);
      sz_SphereEmitter[i] = rng(5.9, 5.9);
      rot_SphereEmitter[i] = rng(0, Math.PI * 2);
      
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(rng(-1, 1));
      const speed = rng(0, 0) * 2.0;
      const srad = 0.01 * 2.0;
      pos_SphereEmitter[i].set(
        x + Math.sin(phi) * Math.cos(theta) * srad,
        y + Math.cos(phi) * srad,
        z + Math.sin(phi) * Math.sin(theta) * srad
      );
      vel_SphereEmitter[i].set(
        Math.sin(phi) * Math.cos(theta) * speed,
        Math.cos(phi) * speed,
        Math.sin(phi) * Math.sin(theta) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_SphereEmitter = 1;
    for (let i = 0; i < Math.min(cnt_SphereEmitter, initialBurst_SphereEmitter); i++) {
      spawnParticle_SphereEmitter(ptr_SphereEmitter);
      ptr_SphereEmitter = (ptr_SphereEmitter + 1) % cnt_SphereEmitter;
    }
  
    const colorKeys_SphereEmitter: ColorKey[] | null = [{ value: { r: 0.00000, g: 1.00000, b: 1.00000 }, pos: 0.00882 }, { value: { r: 0.00000, g: 0.00000, b: 1.00000 }, pos: 0.99413 }];
    const alphaKeys_SphereEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00000 }, { value: 0.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_SphereEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_SphereEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_SphereEmitter >= interval) {
          spawnParticle_SphereEmitter(ptr_SphereEmitter);
          ptr_SphereEmitter = (ptr_SphereEmitter + 1) % cnt_SphereEmitter;
          spawnTimer_SphereEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_SphereEmitter; i++) {
        if (life_SphereEmitter[i] >= maxLife_SphereEmitter[i]) {
          mesh_SphereEmitter.setMatrixAt(i, hideM);
          
          continue;
        }
        life_SphereEmitter[i] += dt;
        const pct = Math.min(1, life_SphereEmitter[i] / maxLife_SphereEmitter[i]);
        if (life_SphereEmitter[i] >= maxLife_SphereEmitter[i]) {
          mesh_SphereEmitter.setMatrixAt(i, hideM);
          
          continue;
        }
        // Physics: gravity + drag
        vel_SphereEmitter[i].y += 0 * dt;
        
        pos_SphereEmitter[i].addScaledVector(vel_SphereEmitter[i], dt);
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 1, p0: 0.71226704, p1: 0.9811159733333332, p2: 1, p3: 1}];
        const scaledSz = sz_SphereEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_SphereEmitter ? evalAlpha(alphaKeys_SphereEmitter, pct) : (1 - pct);
        const col = colorKeys_SphereEmitter ? evalColor(colorKeys_SphereEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_SphereEmitter[i]);
        
        T.quaternion.setFromEuler(new THREE.Euler(0, 0, rot_SphereEmitter[i]));
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_SphereEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [];
        const frameRaw = pct * 1;
        frm_SphereEmitter[i] = Math.min(0, Math.floor(frameRaw));
        opc_SphereEmitter[i] = alpha;
        clr_SphereEmitter[i*3+0] = col.r * cfgColor.r; clr_SphereEmitter[i*3+1] = col.g * cfgColor.g; clr_SphereEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_SphereEmitter.instanceMatrix.needsUpdate = true;
      (mesh_SphereEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SphereEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SphereEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_SphereEmitter);
      geo_SphereEmitter.dispose(); mat_SphereEmitter.dispose();
      (mesh_SphereEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: NovaEmitter  (count=11, life=[0.5, 0.5], speed=[0, 0])
    // Texture: tex_2.png  Grid: 6x3
    // ══════════════════════════════════════════════════════════
    const cnt_NovaEmitter = 11;
    const geo_NovaEmitter = new THREE.PlaneGeometry(1, 1);
    const mat_NovaEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex2 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          float c = mod(aFrame, 6.0); float r = floor(aFrame / 6.0);
          vUv = vec2((c + uv.x) / 6.0, 1.0 - (r + 1.0 - uv.y) / 3.0);
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_NovaEmitter = new THREE.InstancedMesh(geo_NovaEmitter, mat_NovaEmitter, cnt_NovaEmitter);
    mesh_NovaEmitter.frustumCulled = false;
    this.scene.add(mesh_NovaEmitter);
    const frm_NovaEmitter = new Float32Array(cnt_NovaEmitter);
    const opc_NovaEmitter = new Float32Array(cnt_NovaEmitter);
    const clr_NovaEmitter = new Float32Array(cnt_NovaEmitter * 3);
    mesh_NovaEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_NovaEmitter, 1));
    mesh_NovaEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_NovaEmitter, 1));
    mesh_NovaEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_NovaEmitter, 3));

    const life_NovaEmitter: number[] = [];
    const maxLife_NovaEmitter: number[] = [];
    const pos_NovaEmitter: THREE.Vector3[] = [];
    const vel_NovaEmitter: THREE.Vector3[] = [];
    const sz_NovaEmitter: number[] = [];
    const rot_NovaEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_NovaEmitter; i++) {
      life_NovaEmitter.push(1.0);
      maxLife_NovaEmitter.push(1.0);
      pos_NovaEmitter.push(new THREE.Vector3(x, y, z));
      vel_NovaEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_NovaEmitter.push(0);
      rot_NovaEmitter.push(0);
      
    }

    let ptr_NovaEmitter = 0;
    let spawnTimer_NovaEmitter = 0;

    const spawnParticle_NovaEmitter = (i: number) => {
      life_NovaEmitter[i] = 0;
      maxLife_NovaEmitter[i] = rng(0.5, 0.5);
      sz_NovaEmitter[i] = rng(8, 8);
      rot_NovaEmitter[i] = rng(0, Math.PI * 2);
      
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(rng(-1, 1));
      const speed = rng(0, 0) * 2.0;
      const srad = 0 * 2.0;
      pos_NovaEmitter[i].set(
        x + Math.sin(phi) * Math.cos(theta) * srad,
        y + Math.cos(phi) * srad,
        z + Math.sin(phi) * Math.sin(theta) * srad
      );
      vel_NovaEmitter[i].set(
        Math.sin(phi) * Math.cos(theta) * speed,
        Math.cos(phi) * speed,
        Math.sin(phi) * Math.sin(theta) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_NovaEmitter = 1;
    for (let i = 0; i < Math.min(cnt_NovaEmitter, initialBurst_NovaEmitter); i++) {
      spawnParticle_NovaEmitter(ptr_NovaEmitter);
      ptr_NovaEmitter = (ptr_NovaEmitter + 1) % cnt_NovaEmitter;
    }
  
    const colorKeys_NovaEmitter: ColorKey[] | null = [{ value: { r: 0.00000, g: 1.00000, b: 1.00000 }, pos: 0.00882 }, { value: { r: 0.00000, g: 0.00000, b: 1.00000 }, pos: 0.99413 }];
    const alphaKeys_NovaEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00000 }, { value: 1.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_NovaEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_NovaEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_NovaEmitter >= interval) {
          spawnParticle_NovaEmitter(ptr_NovaEmitter);
          ptr_NovaEmitter = (ptr_NovaEmitter + 1) % cnt_NovaEmitter;
          spawnTimer_NovaEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_NovaEmitter; i++) {
        if (life_NovaEmitter[i] >= maxLife_NovaEmitter[i]) {
          mesh_NovaEmitter.setMatrixAt(i, hideM);
          opc_NovaEmitter[i] = 0;
          continue;
        }
        life_NovaEmitter[i] += dt;
        const pct = Math.min(1, life_NovaEmitter[i] / maxLife_NovaEmitter[i]);
        if (life_NovaEmitter[i] >= maxLife_NovaEmitter[i]) {
          mesh_NovaEmitter.setMatrixAt(i, hideM);
          opc_NovaEmitter[i] = 0;
          continue;
        }
        // Physics: gravity + drag
        vel_NovaEmitter[i].y += 0 * dt;
        
        const speed_NovaEmitter = vel_NovaEmitter[i].length();
        const limit_NovaEmitter = 0.7 * 2.0;
        if (speed_NovaEmitter > limit_NovaEmitter) {
          const percent = (speed_NovaEmitter - limit_NovaEmitter) / speed_NovaEmitter;
          vel_NovaEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.09 * dt * 20));
        }
    
        pos_NovaEmitter[i].addScaledVector(vel_NovaEmitter[i], dt);
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 1, p0: 0.6454825, p1: 1.0058953333333334, p2: 1, p3: 1}];
        const scaledSz = sz_NovaEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_NovaEmitter ? evalAlpha(alphaKeys_NovaEmitter, pct) : (1 - pct);
        const col = colorKeys_NovaEmitter ? evalColor(colorKeys_NovaEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_NovaEmitter[i]);
        
        T.quaternion.setFromEuler(new THREE.Euler(0, 0, rot_NovaEmitter[i]));
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_NovaEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [{start: 0, end: 0.21994135, p0: 0, p1: 0, p2: 0, p3: 0}, {start: 0.21994135, end: 1, p0: 0, p1: 5.88819908198844, p2: 11.776397198011562, p3: 17.66459628}];
        const frameRaw = evalPiecewise(frameBez, pct);
        frm_NovaEmitter[i] = Math.min(17, Math.floor(frameRaw));
        opc_NovaEmitter[i] = alpha;
        clr_NovaEmitter[i*3+0] = col.r * cfgColor.r; clr_NovaEmitter[i*3+1] = col.g * cfgColor.g; clr_NovaEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_NovaEmitter.instanceMatrix.needsUpdate = true;
      (mesh_NovaEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_NovaEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_NovaEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_NovaEmitter);
      geo_NovaEmitter.dispose(); mat_NovaEmitter.dispose();
      (mesh_NovaEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: TrailEmitter  (count=300, life=[0.4, 0.8], speed=[0, 0])
    // Texture: tex_0.png  Grid: 2x2
    // ══════════════════════════════════════════════════════════
    const cnt_TrailEmitter = 300;
    const geo_TrailEmitter = new THREE.PlaneGeometry(1, 1);
    const mat_TrailEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex0 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          float c = mod(aFrame, 2.0); float r = floor(aFrame / 2.0);
          vUv = vec2((c + uv.x) / 2.0, 1.0 - (r + 1.0 - uv.y) / 2.0);
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_TrailEmitter = new THREE.InstancedMesh(geo_TrailEmitter, mat_TrailEmitter, cnt_TrailEmitter);
    mesh_TrailEmitter.frustumCulled = false;
    this.scene.add(mesh_TrailEmitter);
    const frm_TrailEmitter = new Float32Array(cnt_TrailEmitter);
    const opc_TrailEmitter = new Float32Array(cnt_TrailEmitter);
    const clr_TrailEmitter = new Float32Array(cnt_TrailEmitter * 3);
    mesh_TrailEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_TrailEmitter, 1));
    mesh_TrailEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_TrailEmitter, 1));
    mesh_TrailEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_TrailEmitter, 3));

    const life_TrailEmitter: number[] = [];
    const maxLife_TrailEmitter: number[] = [];
    const pos_TrailEmitter: THREE.Vector3[] = [];
    const vel_TrailEmitter: THREE.Vector3[] = [];
    const sz_TrailEmitter: number[] = [];
    const rot_TrailEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_TrailEmitter; i++) {
      life_TrailEmitter.push(1.0);
      maxLife_TrailEmitter.push(1.0);
      pos_TrailEmitter.push(new THREE.Vector3(x, y, z));
      vel_TrailEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_TrailEmitter.push(0);
      rot_TrailEmitter.push(0);
      
    }

    let ptr_TrailEmitter = 0;
    let spawnTimer_TrailEmitter = 0;

    const spawnParticle_TrailEmitter = (i: number) => {
      life_TrailEmitter[i] = 0;
      maxLife_TrailEmitter[i] = rng(0.4, 0.8);
      sz_TrailEmitter[i] = rng(1, 0.56875);
      rot_TrailEmitter[i] = rng(0, Math.PI * 2);
      
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(rng(-1, 1));
      const speed = rng(0, 0) * 2.0;
      const srad = 0 * 2.0;
      pos_TrailEmitter[i].set(
        x + Math.sin(phi) * Math.cos(theta) * srad,
        y + Math.cos(phi) * srad,
        z + Math.sin(phi) * Math.sin(theta) * srad
      );
      vel_TrailEmitter[i].set(
        Math.sin(phi) * Math.cos(theta) * speed,
        Math.cos(phi) * speed,
        Math.sin(phi) * Math.sin(theta) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_TrailEmitter = 0;
    for (let i = 0; i < Math.min(cnt_TrailEmitter, initialBurst_TrailEmitter); i++) {
      spawnParticle_TrailEmitter(ptr_TrailEmitter);
      ptr_TrailEmitter = (ptr_TrailEmitter + 1) % cnt_TrailEmitter;
    }
  
    const colorKeys_TrailEmitter: ColorKey[] | null = [{ value: { r: 0.00000, g: 0.37647, b: 0.56471 }, pos: 0.00000 }, { value: { r: 0.17647, g: 0.18039, b: 0.23529 }, pos: 1.00000 }];
    const alphaKeys_TrailEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00000 }, { value: 1.00000, pos: 0.90001 }, { value: 0.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_TrailEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_TrailEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_TrailEmitter >= interval) {
          spawnParticle_TrailEmitter(ptr_TrailEmitter);
          ptr_TrailEmitter = (ptr_TrailEmitter + 1) % cnt_TrailEmitter;
          spawnTimer_TrailEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_TrailEmitter; i++) {
        if (life_TrailEmitter[i] >= maxLife_TrailEmitter[i]) {
          mesh_TrailEmitter.setMatrixAt(i, hideM);
          opc_TrailEmitter[i] = 0;
          continue;
        }
        life_TrailEmitter[i] += dt;
        const pct = Math.min(1, life_TrailEmitter[i] / maxLife_TrailEmitter[i]);
        if (life_TrailEmitter[i] >= maxLife_TrailEmitter[i]) {
          mesh_TrailEmitter.setMatrixAt(i, hideM);
          opc_TrailEmitter[i] = 0;
          continue;
        }
        // Physics: gravity + drag
        vel_TrailEmitter[i].y += 1.9600000000000002 * dt;
        
        const speed_TrailEmitter = vel_TrailEmitter[i].length();
        const limit_TrailEmitter = 0 * 2.0;
        if (speed_TrailEmitter > limit_TrailEmitter) {
          const percent = (speed_TrailEmitter - limit_TrailEmitter) / speed_TrailEmitter;
          vel_TrailEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.05 * dt * 20));
        }
    
        pos_TrailEmitter[i].addScaledVector(vel_TrailEmitter[i], dt);
        
        const rotSpeedBez_TrailEmitter: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0.4065934, p3: 0.4065934}];
        rot_TrailEmitter[i] += evalPiecewise(rotSpeedBez_TrailEmitter, pct) * dt;
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 0.21464643, p0: 0.27548078, p1: 0.27548078, p2: 0.7724670801145349, p3: 0.77080387}, {start: 0.21464643, end: 1, p0: 0.77080387, p1: 0.7647184764478682, p2: 0.6540969042768533, p3: 0}];
        const scaledSz = sz_TrailEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_TrailEmitter ? evalAlpha(alphaKeys_TrailEmitter, pct) : (1 - pct);
        const col = colorKeys_TrailEmitter ? evalColor(colorKeys_TrailEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_TrailEmitter[i]);
        
        T.quaternion.copy(cq);
        T.rotateZ(rot_TrailEmitter[i]);
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_TrailEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [{start: 0, end: 1.0, p0: 0, p1: 0, p2: 3.9996, p3: 3.9996}];
        const frameRaw = evalPiecewise(frameBez, pct);
        frm_TrailEmitter[i] = Math.min(3, Math.floor(frameRaw));
        opc_TrailEmitter[i] = alpha;
        clr_TrailEmitter[i*3+0] = col.r * cfgColor.r; clr_TrailEmitter[i*3+1] = col.g * cfgColor.g; clr_TrailEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_TrailEmitter.instanceMatrix.needsUpdate = true;
      (mesh_TrailEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_TrailEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_TrailEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_TrailEmitter);
      geo_TrailEmitter.dispose(); mat_TrailEmitter.dispose();
      (mesh_TrailEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: SmokeTrailEmitter  (count=14, life=[1, 1.3], speed=[25, 30])
    // Texture: tex_1.png  Grid: 1x1
    // ══════════════════════════════════════════════════════════
    const cnt_SmokeTrailEmitter = 14;
    const geo_SmokeTrailEmitter = new THREE.PlaneGeometry(1, 1);
    const mat_SmokeTrailEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex1 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vUv = uv;
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_SmokeTrailEmitter = new THREE.InstancedMesh(geo_SmokeTrailEmitter, mat_SmokeTrailEmitter, cnt_SmokeTrailEmitter);
    mesh_SmokeTrailEmitter.frustumCulled = false;
    this.scene.add(mesh_SmokeTrailEmitter);
    const frm_SmokeTrailEmitter = new Float32Array(cnt_SmokeTrailEmitter);
    const opc_SmokeTrailEmitter = new Float32Array(cnt_SmokeTrailEmitter);
    const clr_SmokeTrailEmitter = new Float32Array(cnt_SmokeTrailEmitter * 3);
    mesh_SmokeTrailEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_SmokeTrailEmitter, 1));
    mesh_SmokeTrailEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_SmokeTrailEmitter, 1));
    mesh_SmokeTrailEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_SmokeTrailEmitter, 3));

    const life_SmokeTrailEmitter: number[] = [];
    const maxLife_SmokeTrailEmitter: number[] = [];
    const pos_SmokeTrailEmitter: THREE.Vector3[] = [];
    const vel_SmokeTrailEmitter: THREE.Vector3[] = [];
    const sz_SmokeTrailEmitter: number[] = [];
    const rot_SmokeTrailEmitter: number[] = [];
    const accumulatedDist_SmokeTrailEmitter: number[] = [];

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_SmokeTrailEmitter; i++) {
      life_SmokeTrailEmitter.push(1.0);
      maxLife_SmokeTrailEmitter.push(1.0);
      pos_SmokeTrailEmitter.push(new THREE.Vector3(x, y, z));
      vel_SmokeTrailEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_SmokeTrailEmitter.push(0);
      rot_SmokeTrailEmitter.push(0);
      accumulatedDist_SmokeTrailEmitter.push(0);
    }

    let ptr_SmokeTrailEmitter = 0;
    let spawnTimer_SmokeTrailEmitter = 0;

    const spawnParticle_SmokeTrailEmitter = (i: number) => {
      life_SmokeTrailEmitter[i] = 0;
      maxLife_SmokeTrailEmitter[i] = rng(1, 1.3);
      sz_SmokeTrailEmitter[i] = rng(0.45, 0.45);
      rot_SmokeTrailEmitter[i] = rng(0, Math.PI * 2);
      accumulatedDist_SmokeTrailEmitter[i] = 0;
      const u = Math.random();
      const rand = Math.random();
      const theta = u * 6.283185307179586;
      const r = Math.sqrt(rand);
      const sinTheta = Math.sin(theta);
      const cosTheta = Math.cos(theta);
      const pX = r * cosTheta;
      const pY = r * sinTheta;
      
      const angle = 0.5612978874413763 * r;
      const speed = rng(25, 30) * 2.0;
      const srad = 0.4 * 2.0;
      
      pos_SmokeTrailEmitter[i].set(
        x + pX * srad,
        y + pY * srad,
        z
      );
      vel_SmokeTrailEmitter[i].set(
        pX * Math.sin(angle) * speed,
        pY * Math.sin(angle) * speed,
        Math.cos(angle) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_SmokeTrailEmitter = 4;
    for (let i = 0; i < Math.min(cnt_SmokeTrailEmitter, initialBurst_SmokeTrailEmitter); i++) {
      spawnParticle_SmokeTrailEmitter(ptr_SmokeTrailEmitter);
      ptr_SmokeTrailEmitter = (ptr_SmokeTrailEmitter + 1) % cnt_SmokeTrailEmitter;
    }
  
    const colorKeys_SmokeTrailEmitter: ColorKey[] | null = [{ value: { r: 1.00000, g: 1.00000, b: 1.00000 }, pos: 0.00000 }, { value: { r: 1.00000, g: 1.00000, b: 1.00000 }, pos: 1.00000 }];
    const alphaKeys_SmokeTrailEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00000 }, { value: 1.00000, pos: 0.90001 }, { value: 0.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_SmokeTrailEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_SmokeTrailEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_SmokeTrailEmitter >= interval) {
          spawnParticle_SmokeTrailEmitter(ptr_SmokeTrailEmitter);
          ptr_SmokeTrailEmitter = (ptr_SmokeTrailEmitter + 1) % cnt_SmokeTrailEmitter;
          spawnTimer_SmokeTrailEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_SmokeTrailEmitter; i++) {
        if (life_SmokeTrailEmitter[i] >= maxLife_SmokeTrailEmitter[i]) {
          mesh_SmokeTrailEmitter.setMatrixAt(i, hideM);
          
          continue;
        }
        life_SmokeTrailEmitter[i] += dt;
        const pct = Math.min(1, life_SmokeTrailEmitter[i] / maxLife_SmokeTrailEmitter[i]);
        if (life_SmokeTrailEmitter[i] >= maxLife_SmokeTrailEmitter[i]) {
          mesh_SmokeTrailEmitter.setMatrixAt(i, hideM);
          
          continue;
        }
        // Physics: gravity + drag
        vel_SmokeTrailEmitter[i].y += -19.6 * dt;
        
        const speed_SmokeTrailEmitter = vel_SmokeTrailEmitter[i].length();
        const limit_SmokeTrailEmitter = 2 * 2.0;
        if (speed_SmokeTrailEmitter > limit_SmokeTrailEmitter) {
          const percent = (speed_SmokeTrailEmitter - limit_SmokeTrailEmitter) / speed_SmokeTrailEmitter;
          vel_SmokeTrailEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.25 * dt * 20));
        }
    
        pos_SmokeTrailEmitter[i].addScaledVector(vel_SmokeTrailEmitter[i], dt);
        
        const rotSpeedBez_SmokeTrailEmitter: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0.4065934, p3: 0.4065934}];
        rot_SmokeTrailEmitter[i] += evalPiecewise(rotSpeedBez_SmokeTrailEmitter, pct) * dt;
        


        
        const distMoved_SmokeTrailEmitter = vel_SmokeTrailEmitter[i].length() * dt;
        accumulatedDist_SmokeTrailEmitter[i] += distMoved_SmokeTrailEmitter;
        const subDist_SmokeTrailEmitter = 3 > 0 ? (1.0 / 3) * 2.0 : 0;
        if (subDist_SmokeTrailEmitter > 0) {
          while (accumulatedDist_SmokeTrailEmitter[i] >= subDist_SmokeTrailEmitter) {
            spawnParticle_TrailEmitter(ptr_TrailEmitter);
            pos_TrailEmitter[ptr_TrailEmitter].copy(pos_SmokeTrailEmitter[i]);
            ptr_TrailEmitter = (ptr_TrailEmitter + 1) % cnt_TrailEmitter;
            accumulatedDist_SmokeTrailEmitter[i] -= subDist_SmokeTrailEmitter;
          }
        }
        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 1, p0: 0.7692308, p1: 0.7692308, p2: 0.8392857266666668, p3: 0.15934066}];
        const scaledSz = sz_SmokeTrailEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_SmokeTrailEmitter ? evalAlpha(alphaKeys_SmokeTrailEmitter, pct) : (1 - pct);
        const col = colorKeys_SmokeTrailEmitter ? evalColor(colorKeys_SmokeTrailEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_SmokeTrailEmitter[i]);
        
        T.quaternion.copy(cq);
        T.rotateZ(rot_SmokeTrailEmitter[i]);
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_SmokeTrailEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [];
        const frameRaw = pct * 1;
        frm_SmokeTrailEmitter[i] = Math.min(0, Math.floor(frameRaw));
        opc_SmokeTrailEmitter[i] = alpha;
        clr_SmokeTrailEmitter[i*3+0] = col.r * cfgColor.r; clr_SmokeTrailEmitter[i*3+1] = col.g * cfgColor.g; clr_SmokeTrailEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_SmokeTrailEmitter.instanceMatrix.needsUpdate = true;
      (mesh_SmokeTrailEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SmokeTrailEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SmokeTrailEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_SmokeTrailEmitter);
      geo_SmokeTrailEmitter.dispose(); mat_SmokeTrailEmitter.dispose();
      (mesh_SmokeTrailEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: NukeConeExplosionBlueEmitter  (count=11, life=[0.5, 0.5], speed=[0, 0])
    // Texture: tex_3.png  Grid: 1x1
    // ══════════════════════════════════════════════════════════
    const cnt_NukeConeExplosionBlueEmitter = 11;
    const geo_NukeConeExplosionBlueEmitter = new THREE.PlaneGeometry(1, 1);
    const mat_NukeConeExplosionBlueEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex3 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vUv = uv;
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_NukeConeExplosionBlueEmitter = new THREE.InstancedMesh(geo_NukeConeExplosionBlueEmitter, mat_NukeConeExplosionBlueEmitter, cnt_NukeConeExplosionBlueEmitter);
    mesh_NukeConeExplosionBlueEmitter.frustumCulled = false;
    this.scene.add(mesh_NukeConeExplosionBlueEmitter);
    const frm_NukeConeExplosionBlueEmitter = new Float32Array(cnt_NukeConeExplosionBlueEmitter);
    const opc_NukeConeExplosionBlueEmitter = new Float32Array(cnt_NukeConeExplosionBlueEmitter);
    const clr_NukeConeExplosionBlueEmitter = new Float32Array(cnt_NukeConeExplosionBlueEmitter * 3);
    mesh_NukeConeExplosionBlueEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_NukeConeExplosionBlueEmitter, 1));
    mesh_NukeConeExplosionBlueEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_NukeConeExplosionBlueEmitter, 1));
    mesh_NukeConeExplosionBlueEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_NukeConeExplosionBlueEmitter, 3));

    const life_NukeConeExplosionBlueEmitter: number[] = [];
    const maxLife_NukeConeExplosionBlueEmitter: number[] = [];
    const pos_NukeConeExplosionBlueEmitter: THREE.Vector3[] = [];
    const vel_NukeConeExplosionBlueEmitter: THREE.Vector3[] = [];
    const sz_NukeConeExplosionBlueEmitter: number[] = [];
    const rot_NukeConeExplosionBlueEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_NukeConeExplosionBlueEmitter; i++) {
      life_NukeConeExplosionBlueEmitter.push(1.0);
      maxLife_NukeConeExplosionBlueEmitter.push(1.0);
      pos_NukeConeExplosionBlueEmitter.push(new THREE.Vector3(x, y, z));
      vel_NukeConeExplosionBlueEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_NukeConeExplosionBlueEmitter.push(0);
      rot_NukeConeExplosionBlueEmitter.push(0);
      
    }

    let ptr_NukeConeExplosionBlueEmitter = 0;
    let spawnTimer_NukeConeExplosionBlueEmitter = 0;

    const spawnParticle_NukeConeExplosionBlueEmitter = (i: number) => {
      life_NukeConeExplosionBlueEmitter[i] = 0;
      maxLife_NukeConeExplosionBlueEmitter[i] = rng(0.5, 0.5);
      sz_NukeConeExplosionBlueEmitter[i] = rng(12, 12);
      rot_NukeConeExplosionBlueEmitter[i] = rng(0, Math.PI * 2);
      
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(rng(-1, 1));
      const speed = rng(0, 0) * 2.0;
      const srad = 0 * 2.0;
      pos_NukeConeExplosionBlueEmitter[i].set(
        x + Math.sin(phi) * Math.cos(theta) * srad,
        y + Math.cos(phi) * srad,
        z + Math.sin(phi) * Math.sin(theta) * srad
      );
      vel_NukeConeExplosionBlueEmitter[i].set(
        Math.sin(phi) * Math.cos(theta) * speed,
        Math.cos(phi) * speed,
        Math.sin(phi) * Math.sin(theta) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_NukeConeExplosionBlueEmitter = 1;
    for (let i = 0; i < Math.min(cnt_NukeConeExplosionBlueEmitter, initialBurst_NukeConeExplosionBlueEmitter); i++) {
      spawnParticle_NukeConeExplosionBlueEmitter(ptr_NukeConeExplosionBlueEmitter);
      ptr_NukeConeExplosionBlueEmitter = (ptr_NukeConeExplosionBlueEmitter + 1) % cnt_NukeConeExplosionBlueEmitter;
    }
  
    const colorKeys_NukeConeExplosionBlueEmitter: ColorKey[] | null = [{ value: { r: 0.00000, g: 0.79216, b: 1.00000 }, pos: 0.00000 }, { value: { r: 0.00000, g: 0.12941, b: 1.00000 }, pos: 1.00000 }];
    const alphaKeys_NukeConeExplosionBlueEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00000 }, { value: 0.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_NukeConeExplosionBlueEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_NukeConeExplosionBlueEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_NukeConeExplosionBlueEmitter >= interval) {
          spawnParticle_NukeConeExplosionBlueEmitter(ptr_NukeConeExplosionBlueEmitter);
          ptr_NukeConeExplosionBlueEmitter = (ptr_NukeConeExplosionBlueEmitter + 1) % cnt_NukeConeExplosionBlueEmitter;
          spawnTimer_NukeConeExplosionBlueEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_NukeConeExplosionBlueEmitter; i++) {
        if (life_NukeConeExplosionBlueEmitter[i] >= maxLife_NukeConeExplosionBlueEmitter[i]) {
          mesh_NukeConeExplosionBlueEmitter.setMatrixAt(i, hideM);
          
          continue;
        }
        life_NukeConeExplosionBlueEmitter[i] += dt;
        const pct = Math.min(1, life_NukeConeExplosionBlueEmitter[i] / maxLife_NukeConeExplosionBlueEmitter[i]);
        if (life_NukeConeExplosionBlueEmitter[i] >= maxLife_NukeConeExplosionBlueEmitter[i]) {
          mesh_NukeConeExplosionBlueEmitter.setMatrixAt(i, hideM);
          
          continue;
        }
        // Physics: gravity + drag
        vel_NukeConeExplosionBlueEmitter[i].y += 0 * dt;
        
        const speed_NukeConeExplosionBlueEmitter = vel_NukeConeExplosionBlueEmitter[i].length();
        const limit_NukeConeExplosionBlueEmitter = 0.7 * 2.0;
        if (speed_NukeConeExplosionBlueEmitter > limit_NukeConeExplosionBlueEmitter) {
          const percent = (speed_NukeConeExplosionBlueEmitter - limit_NukeConeExplosionBlueEmitter) / speed_NukeConeExplosionBlueEmitter;
          vel_NukeConeExplosionBlueEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.09 * dt * 20));
        }
    
        pos_NukeConeExplosionBlueEmitter[i].addScaledVector(vel_NukeConeExplosionBlueEmitter[i], dt);
        
        const rotSpeedBez_NukeConeExplosionBlueEmitter: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0, p3: 0}];
        rot_NukeConeExplosionBlueEmitter[i] += evalPiecewise(rotSpeedBez_NukeConeExplosionBlueEmitter, pct) * dt;
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0.9249999, p3: 0.6923077}];
        const scaledSz = sz_NukeConeExplosionBlueEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_NukeConeExplosionBlueEmitter ? evalAlpha(alphaKeys_NukeConeExplosionBlueEmitter, pct) : (1 - pct);
        const col = colorKeys_NukeConeExplosionBlueEmitter ? evalColor(colorKeys_NukeConeExplosionBlueEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_NukeConeExplosionBlueEmitter[i]);
        
        T.quaternion.copy(cq);
        T.rotateZ(rot_NukeConeExplosionBlueEmitter[i]);
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_NukeConeExplosionBlueEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [];
        const frameRaw = pct * 1;
        frm_NukeConeExplosionBlueEmitter[i] = Math.min(0, Math.floor(frameRaw));
        opc_NukeConeExplosionBlueEmitter[i] = alpha;
        clr_NukeConeExplosionBlueEmitter[i*3+0] = col.r * cfgColor.r; clr_NukeConeExplosionBlueEmitter[i*3+1] = col.g * cfgColor.g; clr_NukeConeExplosionBlueEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_NukeConeExplosionBlueEmitter.instanceMatrix.needsUpdate = true;
      (mesh_NukeConeExplosionBlueEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_NukeConeExplosionBlueEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_NukeConeExplosionBlueEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_NukeConeExplosionBlueEmitter);
      geo_NukeConeExplosionBlueEmitter.dispose(); mat_NukeConeExplosionBlueEmitter.dispose();
      (mesh_NukeConeExplosionBlueEmitter as THREE.InstancedMesh).dispose();
    });

    // ── Main animation tick ───────────────────────────────────────
    this.activeFX.push({
      update: (dt: number) => {
        age += dt;
        if (age > 3) {
          cleanups.forEach(fn => fn());
          return false;
        }
        const cq = this.camera.quaternion;
        void cq;
        update_SmokeCloudsUpEmitter(dt);
        update_SmokeCloudsEmitter(dt);
        update_SparksEmitter(dt);
        update_FireBallEmitter(dt);
        update_SphereEmitter(dt);
        update_NovaEmitter(dt);
        update_TrailEmitter(dt);
        update_SmokeTrailEmitter(dt);
        update_NukeConeExplosionBlueEmitter(dt);
        return true;
      }
    });
  }

  public update(delta: number) {
    for (let i = this.activeFX.length - 1; i >= 0; i--) {
      if (!this.activeFX[i].update(delta)) this.activeFX.splice(i, 1);
    }
  }
}
