import * as THREE from 'three';
import { CHARACTER_CONFIG } from '../../character/character-config';

// Generated by scripts/quarks-to-native.mjs
// Source: Cartoon Blue Flamethrower.ts
// DO NOT EDIT — re-run the converter to regenerate.

// ─── Bezier/curve helpers ────────────────────────────────────────────────────

function bezier3(p0: number, p1: number, p2: number, p3: number, t: number): number {
  const u = 1 - t; return u*u*u*p0 + 3*u*u*t*p1 + 3*u*t*t*p2 + t*t*t*p3;
}

interface PiecewiseCurve { start: number; end: number; p0: number; p1: number; p2: number; p3: number; }

function evalPiecewise(curves: PiecewiseCurve[], t: number): number {
  if (curves.length === 0) return 0;
  for (let i = 0; i < curves.length; i++) {
    const c = curves[i];
    if (t >= c.start && t <= c.end) {
      const nt = (c.end === c.start) ? 0 : (t - c.start) / (c.end - c.start);
      return bezier3(c.p0, c.p1, c.p2, c.p3, nt);
    }
  }
  if (t < curves[0].start) return bezier3(curves[0].p0, curves[0].p1, curves[0].p2, curves[0].p3, 0);
  const last = curves[curves.length - 1];
  return bezier3(last.p0, last.p1, last.p2, last.p3, 1.0);
}

interface ColorKey { value: { r: number; g: number; b: number }; pos: number; }
interface AlphaKey { value: number; pos: number; }

function evalAlpha(keys: AlphaKey[], t: number): number {
  for (let i = 0; i < keys.length - 1; i++) {
    if (t <= keys[i+1].pos) {
      const lt = (t - keys[i].pos) / (keys[i+1].pos - keys[i].pos);
      return keys[i].value + lt * (keys[i+1].value - keys[i].value);
    }
  }
  return keys[keys.length-1].value;
}

// ponytail: out-param avoids {r,g,b} heap alloc per particle per frame
const _col = { r: 1, g: 1, b: 1 };
function evalColor(keys: ColorKey[], t: number, out: { r: number; g: number; b: number }) {
  for (let i = 0; i < keys.length - 1; i++) {
    if (t <= keys[i+1].pos) {
      const lt = (t - keys[i].pos) / (keys[i+1].pos - keys[i].pos);
      out.r = keys[i].value.r + lt * (keys[i+1].value.r - keys[i].value.r);
      out.g = keys[i].value.g + lt * (keys[i+1].value.g - keys[i].value.g);
      out.b = keys[i].value.b + lt * (keys[i+1].value.b - keys[i].value.b);
      return;
    }
  }
  const last = keys[keys.length-1].value;
  out.r = last.r; out.g = last.g; out.b = last.b;
}

function rng(a: number, b: number) { return a + Math.random() * (b - a); }

// ─── VFX Class ───────────────────────────────────────────────────────────────

export class CartoonBlueFlamethrowerNativeVFX {
  private scene: THREE.Scene;
  private camera: THREE.Camera;
  private activeFX: Array<{ update: (delta: number) => boolean }> = [];
  private tex0: THREE.Texture;
  private tex1: THREE.Texture;
  private tex2: THREE.Texture;
  private tex3: THREE.Texture;

  constructor(scene: THREE.Scene, camera: THREE.Camera) {
    this.scene = scene;
    this.camera = camera;
    const L = new THREE.TextureLoader();
    this.tex0 = L.load('/vfx/cartoon-blue-flamethrower/tex_0.png');
    this.tex1 = L.load('/vfx/cartoon-blue-flamethrower/tex_1.png');
    this.tex2 = L.load('/vfx/cartoon-blue-flamethrower/tex_2.png');
    this.tex3 = L.load('/vfx/cartoon-blue-flamethrower/tex_3.png');
  }

  public spawn(x: number, y: number, z: number, anchor?: THREE.Object3D, duration = 2.0) {
    // ponytail: scratch objects hoisted out of per-frame update — avoids GC pressure at 60fps
    const _anchorPos = new THREE.Vector3();
    const _rotOffset = new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), Math.PI);
    const _localVel = new THREE.Vector3();

    if (anchor) {
      anchor.getWorldPosition(_anchorPos);
      x = _anchorPos.x;
      y = _anchorPos.y + 0.8; // Chest height offset
      z = _anchorPos.z;
    }
    const origin = new THREE.Vector3(x, y, z);
    const originQuat = new THREE.Quaternion();
    if (anchor) {
      anchor.getWorldQuaternion(originQuat);
      originQuat.multiply(_rotOffset);
    }
    const T = new THREE.Object3D();
    const hideM = new THREE.Matrix4().makeScale(0, 0, 0);
    const cq = this.camera.quaternion;
    const cfgColor = new THREE.Color(CHARACTER_CONFIG.skills.flamethrower.hudColor);
    let age = 0;
    const cleanups: (() => void)[] = [];

    // ══════════════════════════════════════════════════════════
    // Emitter: GlowEmitter  (count=22, life=[0.4, 0.4], speed=[21, 21])
    // Texture: tex_0.png  Grid: 1x1
    // ══════════════════════════════════════════════════════════
    const cnt_GlowEmitter = 60;
    const geo_GlowEmitter = new THREE.IcosahedronGeometry(0.35, 1);
    const mat_GlowEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex0 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vUv = uv;
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_GlowEmitter = new THREE.InstancedMesh(geo_GlowEmitter, mat_GlowEmitter, cnt_GlowEmitter);
    mesh_GlowEmitter.frustumCulled = false;
    this.scene.add(mesh_GlowEmitter);
    const frm_GlowEmitter = new Float32Array(cnt_GlowEmitter);
    const opc_GlowEmitter = new Float32Array(cnt_GlowEmitter);
    const clr_GlowEmitter = new Float32Array(cnt_GlowEmitter * 3);
    mesh_GlowEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_GlowEmitter, 1));
    mesh_GlowEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_GlowEmitter, 1));
    mesh_GlowEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_GlowEmitter, 3));

    const life_GlowEmitter: number[] = [];
    const maxLife_GlowEmitter: number[] = [];
    const pos_GlowEmitter: THREE.Vector3[] = [];
    const vel_GlowEmitter: THREE.Vector3[] = [];
    const sz_GlowEmitter: number[] = [];
    const rot_GlowEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_GlowEmitter; i++) {
      life_GlowEmitter.push(1.0);
      maxLife_GlowEmitter.push(1.0);
      pos_GlowEmitter.push(new THREE.Vector3(x, y, z));
      vel_GlowEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_GlowEmitter.push(0);
      rot_GlowEmitter.push(0);
      
    }

    let ptr_GlowEmitter = 0;
    let spawnTimer_GlowEmitter = 0;

    const spawnParticle_GlowEmitter = (i: number) => {
      life_GlowEmitter[i] = 0;
      maxLife_GlowEmitter[i] = rng(0.7, 0.9);
      sz_GlowEmitter[i] = rng(0.8, 1.0);
      rot_GlowEmitter[i] = rng(0, Math.PI * 2);
      
      const u = Math.random();
      const rand = Math.random();
      const theta = u * 6.283185307179586;
      const r = Math.sqrt(rand);
      const sinTheta = Math.sin(theta);
      const cosTheta = Math.cos(theta);
      const pX = r * cosTheta;
      const pY = r * sinTheta;
      
      const angle = 0 * r;
      const speed = rng(21, 21) * 1.1;
      const srad = 0.01 * 2.0;
      
      pos_GlowEmitter[i].set(
        origin.x + pX * srad,
        origin.y + pY * srad,
        origin.z
      );
      _localVel.set(
        pX * Math.sin(angle) * speed,
        pY * Math.sin(angle) * speed,
        Math.cos(angle) * speed
      );
      if (anchor) {
        _localVel.applyQuaternion(originQuat);
      }
      vel_GlowEmitter[i].copy(_localVel);
    };

    // Trigger initial bursts
    const initialBurst_GlowEmitter = 0;
    for (let i = 0; i < Math.min(cnt_GlowEmitter, initialBurst_GlowEmitter); i++) {
      spawnParticle_GlowEmitter(ptr_GlowEmitter);
      ptr_GlowEmitter = (ptr_GlowEmitter + 1) % cnt_GlowEmitter;
    }
  
    const colorKeys_GlowEmitter: ColorKey[] | null = [{ value: { r: 1.00000, g: 1.00000, b: 1.00000 }, pos: 0.00000 }, { value: { r: 1.00000, g: 1.00000, b: 1.00000 }, pos: 1.00000 }];
    const alphaKeys_GlowEmitter: AlphaKey[] | null = [{ value: 0.00000, pos: 0.00000 }, { value: 0.40000, pos: 0.56136 }, { value: 0.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_GlowEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 25;
      if (rate > 0) {
        spawnTimer_GlowEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_GlowEmitter >= interval) {
          spawnParticle_GlowEmitter(ptr_GlowEmitter);
          ptr_GlowEmitter = (ptr_GlowEmitter + 1) % cnt_GlowEmitter;
          spawnTimer_GlowEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_GlowEmitter; i++) {
        if (life_GlowEmitter[i] >= maxLife_GlowEmitter[i]) {
          mesh_GlowEmitter.setMatrixAt(i, hideM);
          
          continue;
        }
        life_GlowEmitter[i] += dt;
        const pct = Math.min(1, life_GlowEmitter[i] / maxLife_GlowEmitter[i]);
        if (life_GlowEmitter[i] >= maxLife_GlowEmitter[i]) {
          mesh_GlowEmitter.setMatrixAt(i, hideM);
          
          continue;
        }
        // Physics: gravity + drag
        vel_GlowEmitter[i].y += 0 * dt;
        
        const speed_GlowEmitter = vel_GlowEmitter[i].length();
        const limit_GlowEmitter = 0 * 2.0;
        if (speed_GlowEmitter > limit_GlowEmitter) {
          const percent = (speed_GlowEmitter - limit_GlowEmitter) / speed_GlowEmitter;
          vel_GlowEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.15 * dt * 20));
        }
    
        pos_GlowEmitter[i].addScaledVector(vel_GlowEmitter[i], dt);
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 1, p0: 0.50585485, p1: 0.9315768833333333, p2: 0.9504639766666667, p3: 1}];
        const scaledSz = sz_GlowEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_GlowEmitter ? evalAlpha(alphaKeys_GlowEmitter, pct) : (1 - pct);
        if (colorKeys_GlowEmitter) evalColor(colorKeys_GlowEmitter, pct, _col); else { _col.r = 1; _col.g = 1; _col.b = 1; }
        const col = _col;

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_GlowEmitter[i]);
        
        T.quaternion.copy(cq);
        T.rotateZ(rot_GlowEmitter[i]);
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_GlowEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [];
        const frameRaw = pct * 1;
        frm_GlowEmitter[i] = Math.min(0, Math.floor(frameRaw));
        opc_GlowEmitter[i] = alpha;
        clr_GlowEmitter[i*3+0] = col.r * cfgColor.r; clr_GlowEmitter[i*3+1] = col.g * cfgColor.g; clr_GlowEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_GlowEmitter.instanceMatrix.needsUpdate = true;
      (mesh_GlowEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_GlowEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_GlowEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_GlowEmitter);
      geo_GlowEmitter.dispose(); mat_GlowEmitter.dispose();
      (mesh_GlowEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: SmokeEmitter  (count=87, life=[0.5, 1.1], speed=[30, 35])
    // Texture: tex_1.png  Grid: 2x2
    // ══════════════════════════════════════════════════════════
    const cnt_SmokeEmitter = 250;
    const geo_SmokeEmitter = new THREE.IcosahedronGeometry(0.4, 1);
    const mat_SmokeEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex1 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          float c = mod(aFrame, 2.0); float r = floor(aFrame / 2.0);
          vUv = vec2((c + uv.x) / 2.0, 1.0 - (r + 1.0 - uv.y) / 2.0);
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_SmokeEmitter = new THREE.InstancedMesh(geo_SmokeEmitter, mat_SmokeEmitter, cnt_SmokeEmitter);
    mesh_SmokeEmitter.frustumCulled = false;
    this.scene.add(mesh_SmokeEmitter);
    const frm_SmokeEmitter = new Float32Array(cnt_SmokeEmitter);
    const opc_SmokeEmitter = new Float32Array(cnt_SmokeEmitter);
    const clr_SmokeEmitter = new Float32Array(cnt_SmokeEmitter * 3);
    mesh_SmokeEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_SmokeEmitter, 1));
    mesh_SmokeEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_SmokeEmitter, 1));
    mesh_SmokeEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_SmokeEmitter, 3));

    const life_SmokeEmitter: number[] = [];
    const maxLife_SmokeEmitter: number[] = [];
    const pos_SmokeEmitter: THREE.Vector3[] = [];
    const vel_SmokeEmitter: THREE.Vector3[] = [];
    const sz_SmokeEmitter: number[] = [];
    const rot_SmokeEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_SmokeEmitter; i++) {
      life_SmokeEmitter.push(1.0);
      maxLife_SmokeEmitter.push(1.0);
      pos_SmokeEmitter.push(new THREE.Vector3(x, y, z));
      vel_SmokeEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_SmokeEmitter.push(0);
      rot_SmokeEmitter.push(0);
      
    }

    let ptr_SmokeEmitter = 0;
    let spawnTimer_SmokeEmitter = 0;

    const spawnParticle_SmokeEmitter = (i: number) => {
      life_SmokeEmitter[i] = 0;
      maxLife_SmokeEmitter[i] = rng(0.9, 1.8);
      sz_SmokeEmitter[i] = rng(0.65, 0.85);
      rot_SmokeEmitter[i] = rng(0, Math.PI * 2);
      
      const u = Math.random();
      const rand = Math.random();
      const theta = u * 6.283185307179586;
      const r = Math.sqrt(rand);
      const sinTheta = Math.sin(theta);
      const cosTheta = Math.cos(theta);
      const pX = r * cosTheta;
      const pY = r * sinTheta;
      
      const angle = 0.12217304763960307 * r;
      const speed = rng(30, 35) * 1.0;
      const srad = 0.01 * 2.0;
      
      pos_SmokeEmitter[i].set(
        origin.x + pX * srad,
        origin.y + pY * srad,
        origin.z
      );
      _localVel.set(
        pX * Math.sin(angle) * speed,
        pY * Math.sin(angle) * speed,
        Math.cos(angle) * speed
      );
      if (anchor) {
        _localVel.applyQuaternion(originQuat);
      }
      vel_SmokeEmitter[i].copy(_localVel);
    };

    // Trigger initial bursts
    const initialBurst_SmokeEmitter = 0;
    for (let i = 0; i < Math.min(cnt_SmokeEmitter, initialBurst_SmokeEmitter); i++) {
      spawnParticle_SmokeEmitter(ptr_SmokeEmitter);
      ptr_SmokeEmitter = (ptr_SmokeEmitter + 1) % cnt_SmokeEmitter;
    }
  
    const colorKeys_SmokeEmitter: ColorKey[] | null = [{ value: { r: 0.00000, g: 1.00000, b: 1.00000 }, pos: 0.00000 }, { value: { r: 0.09020, g: 0.39786, b: 0.65490 }, pos: 0.32552 }, { value: { r: 0.19216, g: 0.19216, b: 0.19216 }, pos: 1.00000 }];
    const alphaKeys_SmokeEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00000 }, { value: 1.00000, pos: 0.90001 }, { value: 0.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_SmokeEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 80;
      if (rate > 0) {
        spawnTimer_SmokeEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_SmokeEmitter >= interval) {
          spawnParticle_SmokeEmitter(ptr_SmokeEmitter);
          ptr_SmokeEmitter = (ptr_SmokeEmitter + 1) % cnt_SmokeEmitter;
          spawnTimer_SmokeEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_SmokeEmitter; i++) {
        if (life_SmokeEmitter[i] >= maxLife_SmokeEmitter[i]) {
          mesh_SmokeEmitter.setMatrixAt(i, hideM);
          opc_SmokeEmitter[i] = 0;
          continue;
        }
        life_SmokeEmitter[i] += dt;
        const pct = Math.min(1, life_SmokeEmitter[i] / maxLife_SmokeEmitter[i]);
        if (life_SmokeEmitter[i] >= maxLife_SmokeEmitter[i]) {
          mesh_SmokeEmitter.setMatrixAt(i, hideM);
          opc_SmokeEmitter[i] = 0;
          continue;
        }
        // Physics: gravity + drag
        vel_SmokeEmitter[i].y += 11.76 * dt;
        
        const speed_SmokeEmitter = vel_SmokeEmitter[i].length();
        const limit_SmokeEmitter = 0 * 2.0;
        if (speed_SmokeEmitter > limit_SmokeEmitter) {
          const percent = (speed_SmokeEmitter - limit_SmokeEmitter) / speed_SmokeEmitter;
          vel_SmokeEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.2 * dt * 20));
        }
    
        pos_SmokeEmitter[i].addScaledVector(vel_SmokeEmitter[i], dt);
        
        const rotSpeedBez_SmokeEmitter: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0, p3: 0}];
        rot_SmokeEmitter[i] += evalPiecewise(rotSpeedBez_SmokeEmitter, pct) * dt;
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 0.40083522, p0: 0, p1: 0, p2: 0.7312475963931631, p3: 0.83933115}, {start: 0.40083522, end: 1, p0: 0.83933115, p1: 1.000893446393163, p2: 0.3994431866666666, p3: 0}];
        const scaledSz = sz_SmokeEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_SmokeEmitter ? evalAlpha(alphaKeys_SmokeEmitter, pct) : (1 - pct);
        if (colorKeys_SmokeEmitter) evalColor(colorKeys_SmokeEmitter, pct, _col); else { _col.r = 1; _col.g = 1; _col.b = 1; }
        const col = _col;

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_SmokeEmitter[i]);
        
        T.quaternion.copy(cq);
        T.rotateZ(rot_SmokeEmitter[i]);
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_SmokeEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [{start: 0, end: 1.0, p0: 0, p1: 0, p2: 3.9996, p3: 3.9996}];
        const frameRaw = evalPiecewise(frameBez, pct);
        frm_SmokeEmitter[i] = Math.min(3, Math.floor(frameRaw));
        opc_SmokeEmitter[i] = alpha;
        clr_SmokeEmitter[i*3+0] = col.r * cfgColor.r; clr_SmokeEmitter[i*3+1] = col.g * cfgColor.g; clr_SmokeEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_SmokeEmitter.instanceMatrix.needsUpdate = true;
      (mesh_SmokeEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SmokeEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SmokeEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_SmokeEmitter);
      geo_SmokeEmitter.dispose(); mat_SmokeEmitter.dispose();
      (mesh_SmokeEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: EmbersEmitter  (count=68, life=[0.4, 1.2], speed=[16, 17])
    // Texture: tex_2.png  Grid: 1x1
    // ══════════════════════════════════════════════════════════
    const cnt_EmbersEmitter = 200;
    const geo_EmbersEmitter = new THREE.BoxGeometry(0.12, 0.12, 0.12);
    const mat_EmbersEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex2 }, speedFactor: { value: 0.0100 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor; attribute vec3 aVelocity; attribute vec3 aOffset;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        uniform float speedFactor;
        void main() {
          float c = mod(aFrame, 1.0); float r = floor(aFrame / 1.0);
          vUv = vec2((c + uv.x) / 1.0, 1.0 - (r + 1.0 - uv.y) / 1.0);
          vOpacity = aOpacity; vColor = aColor;
          vec4 mvPos = modelViewMatrix * vec4(aOffset, 1.0);
          vec3 viewVel = normalMatrix * aVelocity;
          float vlength = length(viewVel);
          float avgSize = (instanceMatrix[0][0] + instanceMatrix[1][1]) * 0.5;
          float sz = length(vec3(instanceMatrix[0][0], instanceMatrix[0][1], instanceMatrix[0][2]));
          mvPos.xyz += position.y * normalize(cross(mvPos.xyz, viewVel)) * sz;
          mvPos.xyz -= (position.x + 0.5) * viewVel * (1.0 + 1.0000 / max(vlength, 0.001)) * sz;
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * mvPos;
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.NormalBlending
    });
    const mesh_EmbersEmitter = new THREE.InstancedMesh(geo_EmbersEmitter, mat_EmbersEmitter, cnt_EmbersEmitter);
    mesh_EmbersEmitter.frustumCulled = false;
    this.scene.add(mesh_EmbersEmitter);
    const frm_EmbersEmitter = new Float32Array(cnt_EmbersEmitter);
    const opc_EmbersEmitter = new Float32Array(cnt_EmbersEmitter);
    const clr_EmbersEmitter = new Float32Array(cnt_EmbersEmitter * 3);
    mesh_EmbersEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_EmbersEmitter, 1));
    mesh_EmbersEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_EmbersEmitter, 1));
    mesh_EmbersEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_EmbersEmitter, 3));
    const vel_buf_EmbersEmitter = new Float32Array(cnt_EmbersEmitter * 3);
    const off_buf_EmbersEmitter = new Float32Array(cnt_EmbersEmitter * 3);
    mesh_EmbersEmitter.geometry.setAttribute('aVelocity', new THREE.InstancedBufferAttribute(vel_buf_EmbersEmitter, 3));
    mesh_EmbersEmitter.geometry.setAttribute('aOffset', new THREE.InstancedBufferAttribute(off_buf_EmbersEmitter, 3));

    const life_EmbersEmitter: number[] = [];
    const maxLife_EmbersEmitter: number[] = [];
    const pos_EmbersEmitter: THREE.Vector3[] = [];
    const vel_EmbersEmitter: THREE.Vector3[] = [];
    const sz_EmbersEmitter: number[] = [];
    const rot_EmbersEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_EmbersEmitter; i++) {
      life_EmbersEmitter.push(1.0);
      maxLife_EmbersEmitter.push(1.0);
      pos_EmbersEmitter.push(new THREE.Vector3(x, y, z));
      vel_EmbersEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_EmbersEmitter.push(0);
      rot_EmbersEmitter.push(0);
      
    }

    let ptr_EmbersEmitter = 0;
    let spawnTimer_EmbersEmitter = 0;

    const spawnParticle_EmbersEmitter = (i: number) => {
      life_EmbersEmitter[i] = 0;
      maxLife_EmbersEmitter[i] = rng(0.8, 1.8);
      sz_EmbersEmitter[i] = rng(0.07, 0.10);
      rot_EmbersEmitter[i] = rng(0, Math.PI * 2);
      
      const u = Math.random();
      const rand = Math.random();
      const theta = u * 6.283185307179586;
      const r = Math.sqrt(rand);
      const sinTheta = Math.sin(theta);
      const cosTheta = Math.cos(theta);
      const pX = r * cosTheta;
      const pY = r * sinTheta;
      
      const angle = 0.28064894372068816 * r;
      const speed = rng(16, 17) * 1.1;
      const srad = 0.01 * 2.0;
      
      pos_EmbersEmitter[i].set(
        origin.x + pX * srad,
        origin.y + pY * srad,
        origin.z
      );
      _localVel.set(
        pX * Math.sin(angle) * speed,
        pY * Math.sin(angle) * speed,
        Math.cos(angle) * speed
      );
      if (anchor) {
        _localVel.applyQuaternion(originQuat);
      }
      vel_EmbersEmitter[i].copy(_localVel);
    };

    // Trigger initial bursts
    const initialBurst_EmbersEmitter = 0;
    for (let i = 0; i < Math.min(cnt_EmbersEmitter, initialBurst_EmbersEmitter); i++) {
      spawnParticle_EmbersEmitter(ptr_EmbersEmitter);
      ptr_EmbersEmitter = (ptr_EmbersEmitter + 1) % cnt_EmbersEmitter;
    }
  
    const colorKeys_EmbersEmitter: ColorKey[] | null = [{ value: { r: 1.00000, g: 1.00000, b: 1.00000 }, pos: 0.00882 }, { value: { r: 0.00000, g: 1.00000, b: 1.00000 }, pos: 0.99413 }];
    const alphaKeys_EmbersEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00439 }, { value: 1.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_EmbersEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 60;
      if (rate > 0) {
        spawnTimer_EmbersEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_EmbersEmitter >= interval) {
          spawnParticle_EmbersEmitter(ptr_EmbersEmitter);
          ptr_EmbersEmitter = (ptr_EmbersEmitter + 1) % cnt_EmbersEmitter;
          spawnTimer_EmbersEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_EmbersEmitter; i++) {
        if (life_EmbersEmitter[i] >= maxLife_EmbersEmitter[i]) {
          mesh_EmbersEmitter.setMatrixAt(i, hideM);
          opc_EmbersEmitter[i] = 0;
          continue;
        }
        life_EmbersEmitter[i] += dt;
        const pct = Math.min(1, life_EmbersEmitter[i] / maxLife_EmbersEmitter[i]);
        if (life_EmbersEmitter[i] >= maxLife_EmbersEmitter[i]) {
          mesh_EmbersEmitter.setMatrixAt(i, hideM);
          opc_EmbersEmitter[i] = 0;
          continue;
        }
        // Physics: gravity + drag
        vel_EmbersEmitter[i].y += 5.88 * dt;
        
        const speed_EmbersEmitter = vel_EmbersEmitter[i].length();
        const limit_EmbersEmitter = 0.7 * 2.0;
        if (speed_EmbersEmitter > limit_EmbersEmitter) {
          const percent = (speed_EmbersEmitter - limit_EmbersEmitter) / speed_EmbersEmitter;
          vel_EmbersEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.15 * dt * 20));
        }
    
        pos_EmbersEmitter[i].addScaledVector(vel_EmbersEmitter[i], dt);
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 0.3684014, p0: 0.18110657, p1: 0.6493777458853933, p2: 0.9957915115279413, p3: 0.9608776}, {start: 0.3684014, end: 1, p0: 0.9608776, p1: 0.9010201248612747, p2: 0.029164688532285335, p3: 0}];
        const scaledSz = sz_EmbersEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_EmbersEmitter ? evalAlpha(alphaKeys_EmbersEmitter, pct) : (1 - pct);
        if (colorKeys_EmbersEmitter) evalColor(colorKeys_EmbersEmitter, pct, _col); else { _col.r = 1; _col.g = 1; _col.b = 1; }
        const col = _col;

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        // StretchedBillboard: shader handles orientation via aVelocity/aOffset
        T.scale.setScalar(scaledSz);
        off_buf_EmbersEmitter[i*3+0] = pos_EmbersEmitter[i].x;
        off_buf_EmbersEmitter[i*3+1] = pos_EmbersEmitter[i].y;
        off_buf_EmbersEmitter[i*3+2] = pos_EmbersEmitter[i].z;
        vel_buf_EmbersEmitter[i*3+0] = vel_EmbersEmitter[i].x * 0.0100;
        vel_buf_EmbersEmitter[i*3+1] = vel_EmbersEmitter[i].y * 0.0100;
        vel_buf_EmbersEmitter[i*3+2] = vel_EmbersEmitter[i].z * 0.0100;
        
        T.updateMatrix();
        mesh_EmbersEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [];
        const frameRaw = pct * 1;
        frm_EmbersEmitter[i] = Math.min(0, Math.floor(frameRaw));
        opc_EmbersEmitter[i] = alpha;
        clr_EmbersEmitter[i*3+0] = col.r * cfgColor.r; clr_EmbersEmitter[i*3+1] = col.g * cfgColor.g; clr_EmbersEmitter[i*3+2] = col.b * cfgColor.b;
        mesh_EmbersEmitter.geometry.attributes.aVelocity.needsUpdate = true;
        mesh_EmbersEmitter.geometry.attributes.aOffset.needsUpdate = true;
      }
      mesh_EmbersEmitter.instanceMatrix.needsUpdate = true;
      (mesh_EmbersEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_EmbersEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_EmbersEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_EmbersEmitter);
      geo_EmbersEmitter.dispose(); mat_EmbersEmitter.dispose();
      (mesh_EmbersEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: FlamethrowerSharpBlueEmitter  (count=35, life=[0.5, 0.5], speed=[21.6, 21.6])
    // Texture: tex_3.png  Grid: 3x6
    // ══════════════════════════════════════════════════════════
    const cnt_FlamethrowerSharpBlueEmitter = 100;
    const geo_FlamethrowerSharpBlueEmitter = new THREE.IcosahedronGeometry(0.3, 1);
    const mat_FlamethrowerSharpBlueEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex3 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          float c = mod(aFrame, 3.0); float r = floor(aFrame / 3.0);
          vUv = vec2((c + uv.x) / 3.0, 1.0 - (r + 1.0 - uv.y) / 6.0);
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_FlamethrowerSharpBlueEmitter = new THREE.InstancedMesh(geo_FlamethrowerSharpBlueEmitter, mat_FlamethrowerSharpBlueEmitter, cnt_FlamethrowerSharpBlueEmitter);
    mesh_FlamethrowerSharpBlueEmitter.frustumCulled = false;
    this.scene.add(mesh_FlamethrowerSharpBlueEmitter);
    const frm_FlamethrowerSharpBlueEmitter = new Float32Array(cnt_FlamethrowerSharpBlueEmitter);
    const opc_FlamethrowerSharpBlueEmitter = new Float32Array(cnt_FlamethrowerSharpBlueEmitter);
    const clr_FlamethrowerSharpBlueEmitter = new Float32Array(cnt_FlamethrowerSharpBlueEmitter * 3);
    mesh_FlamethrowerSharpBlueEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_FlamethrowerSharpBlueEmitter, 1));
    mesh_FlamethrowerSharpBlueEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_FlamethrowerSharpBlueEmitter, 1));
    mesh_FlamethrowerSharpBlueEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_FlamethrowerSharpBlueEmitter, 3));

    const life_FlamethrowerSharpBlueEmitter: number[] = [];
    const maxLife_FlamethrowerSharpBlueEmitter: number[] = [];
    const pos_FlamethrowerSharpBlueEmitter: THREE.Vector3[] = [];
    const vel_FlamethrowerSharpBlueEmitter: THREE.Vector3[] = [];
    const sz_FlamethrowerSharpBlueEmitter: number[] = [];
    const rot_FlamethrowerSharpBlueEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_FlamethrowerSharpBlueEmitter; i++) {
      life_FlamethrowerSharpBlueEmitter.push(1.0);
      maxLife_FlamethrowerSharpBlueEmitter.push(1.0);
      pos_FlamethrowerSharpBlueEmitter.push(new THREE.Vector3(x, y, z));
      vel_FlamethrowerSharpBlueEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_FlamethrowerSharpBlueEmitter.push(0);
      rot_FlamethrowerSharpBlueEmitter.push(0);
      
    }

    let ptr_FlamethrowerSharpBlueEmitter = 0;
    let spawnTimer_FlamethrowerSharpBlueEmitter = 0;

    const spawnParticle_FlamethrowerSharpBlueEmitter = (i: number) => {
      life_FlamethrowerSharpBlueEmitter[i] = 0;
      maxLife_FlamethrowerSharpBlueEmitter[i] = rng(0.9, 1.1);
      sz_FlamethrowerSharpBlueEmitter[i] = rng(0.9, 1.5);
      rot_FlamethrowerSharpBlueEmitter[i] = rng(0, Math.PI * 2);
      
      const u = Math.random();
      const rand = Math.random();
      const theta = u * 6.283185307179586;
      const r = Math.sqrt(rand);
      const sinTheta = Math.sin(theta);
      const cosTheta = Math.cos(theta);
      const pX = r * cosTheta;
      const pY = r * sinTheta;
      
      const angle = 0.03490658503988659 * r;
      const speed = rng(21.6, 21.6) * 1.0;
      const srad = 0.01 * 2.0;
      
      pos_FlamethrowerSharpBlueEmitter[i].set(
        origin.x + pX * srad,
        origin.y + pY * srad,
        origin.z
      );
      _localVel.set(
        pX * Math.sin(angle) * speed,
        pY * Math.sin(angle) * speed,
        Math.cos(angle) * speed
      );
      if (anchor) {
        _localVel.applyQuaternion(originQuat);
      }
      vel_FlamethrowerSharpBlueEmitter[i].copy(_localVel);
    };

    // Trigger initial bursts
    const initialBurst_FlamethrowerSharpBlueEmitter = 0;
    for (let i = 0; i < Math.min(cnt_FlamethrowerSharpBlueEmitter, initialBurst_FlamethrowerSharpBlueEmitter); i++) {
      spawnParticle_FlamethrowerSharpBlueEmitter(ptr_FlamethrowerSharpBlueEmitter);
      ptr_FlamethrowerSharpBlueEmitter = (ptr_FlamethrowerSharpBlueEmitter + 1) % cnt_FlamethrowerSharpBlueEmitter;
    }
  
    const colorKeys_FlamethrowerSharpBlueEmitter: ColorKey[] | null = [{ value: { r: 1.00000, g: 1.00000, b: 1.00000 }, pos: 0.00000 }, { value: { r: 0.00000, g: 1.00000, b: 1.00000 }, pos: 1.00000 }];
    const alphaKeys_FlamethrowerSharpBlueEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.26394 }, { value: 1.00000, pos: 0.90001 }];

    // Update closure captured for this emitter
    const update_FlamethrowerSharpBlueEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 60;
      if (rate > 0) {
        spawnTimer_FlamethrowerSharpBlueEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_FlamethrowerSharpBlueEmitter >= interval) {
          spawnParticle_FlamethrowerSharpBlueEmitter(ptr_FlamethrowerSharpBlueEmitter);
          ptr_FlamethrowerSharpBlueEmitter = (ptr_FlamethrowerSharpBlueEmitter + 1) % cnt_FlamethrowerSharpBlueEmitter;
          spawnTimer_FlamethrowerSharpBlueEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_FlamethrowerSharpBlueEmitter; i++) {
        if (life_FlamethrowerSharpBlueEmitter[i] >= maxLife_FlamethrowerSharpBlueEmitter[i]) {
          mesh_FlamethrowerSharpBlueEmitter.setMatrixAt(i, hideM);
          opc_FlamethrowerSharpBlueEmitter[i] = 0;
          continue;
        }
        life_FlamethrowerSharpBlueEmitter[i] += dt;
        const pct = Math.min(1, life_FlamethrowerSharpBlueEmitter[i] / maxLife_FlamethrowerSharpBlueEmitter[i]);
        if (life_FlamethrowerSharpBlueEmitter[i] >= maxLife_FlamethrowerSharpBlueEmitter[i]) {
          mesh_FlamethrowerSharpBlueEmitter.setMatrixAt(i, hideM);
          opc_FlamethrowerSharpBlueEmitter[i] = 0;
          continue;
        }
        // Physics: gravity + drag
        vel_FlamethrowerSharpBlueEmitter[i].y += 5.88 * dt;
        
        const speed_FlamethrowerSharpBlueEmitter = vel_FlamethrowerSharpBlueEmitter[i].length();
        const limit_FlamethrowerSharpBlueEmitter = 0 * 2.0;
        if (speed_FlamethrowerSharpBlueEmitter > limit_FlamethrowerSharpBlueEmitter) {
          const percent = (speed_FlamethrowerSharpBlueEmitter - limit_FlamethrowerSharpBlueEmitter) / speed_FlamethrowerSharpBlueEmitter;
          vel_FlamethrowerSharpBlueEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.15 * dt * 20));
        }
    
        pos_FlamethrowerSharpBlueEmitter[i].addScaledVector(vel_FlamethrowerSharpBlueEmitter[i], dt);
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 0.12238693, p0: 0, p1: 0, p2: 0.12425623713983401, p3: 0.1889801}, {start: 0.12238693, end: 1, p0: 0.1889801, p1: 0.653102437139834, p2: 1, p3: 1}];
        const scaledSz = sz_FlamethrowerSharpBlueEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_FlamethrowerSharpBlueEmitter ? evalAlpha(alphaKeys_FlamethrowerSharpBlueEmitter, pct) : (1 - pct);
        if (colorKeys_FlamethrowerSharpBlueEmitter) evalColor(colorKeys_FlamethrowerSharpBlueEmitter, pct, _col); else { _col.r = 1; _col.g = 1; _col.b = 1; }
        const col = _col;

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_FlamethrowerSharpBlueEmitter[i]);
        
        T.quaternion.copy(cq);
        T.rotateZ(rot_FlamethrowerSharpBlueEmitter[i]);
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_FlamethrowerSharpBlueEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [{start: 0, end: 0.20596828, p0: 0, p1: 0, p2: 0, p3: 0}, {start: 0.20596828, end: 1, p0: 0, p1: 2.1750250589181648, p2: 3.757453991198066, p3: 18}];
        const frameRaw = evalPiecewise(frameBez, pct);
        frm_FlamethrowerSharpBlueEmitter[i] = Math.min(17, Math.floor(frameRaw));
        opc_FlamethrowerSharpBlueEmitter[i] = alpha;
        clr_FlamethrowerSharpBlueEmitter[i*3+0] = col.r * cfgColor.r; clr_FlamethrowerSharpBlueEmitter[i*3+1] = col.g * cfgColor.g; clr_FlamethrowerSharpBlueEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_FlamethrowerSharpBlueEmitter.instanceMatrix.needsUpdate = true;
      (mesh_FlamethrowerSharpBlueEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_FlamethrowerSharpBlueEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_FlamethrowerSharpBlueEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_FlamethrowerSharpBlueEmitter);
      geo_FlamethrowerSharpBlueEmitter.dispose(); mat_FlamethrowerSharpBlueEmitter.dispose();
      (mesh_FlamethrowerSharpBlueEmitter as THREE.InstancedMesh).dispose();
    });

    // ── Main animation tick ───────────────────────────────────────
    this.activeFX.push({
      update: (dt: number) => {
        age += dt;
        if (age > duration) {
          cleanups.forEach(fn => fn());
          return false;
        }

        // Keep origin and originQuat attached to the body anchor if provided
        if (anchor) {
          anchor.getWorldPosition(_anchorPos);
          _anchorPos.y += 0.8; // chest height offset
          origin.copy(_anchorPos);

          anchor.getWorldQuaternion(originQuat);
          originQuat.multiply(_rotOffset);
        }

        const cq = this.camera.quaternion;
        void cq;
        update_GlowEmitter(dt);
        update_SmokeEmitter(dt);
        update_EmbersEmitter(dt);
        update_FlamethrowerSharpBlueEmitter(dt);
        return true;
      }
    });
  }

  public update(delta: number) {
    for (let i = this.activeFX.length - 1; i >= 0; i--) {
      if (!this.activeFX[i].update(delta)) this.activeFX.splice(i, 1);
    }
  }
}
