import * as THREE from 'three';
import { CHARACTER_CONFIG } from '../../character/character-config';

// Generated by scripts/quarks-to-native.mjs
// Source: Cartoon Blue Gas Explosion.ts
// DO NOT EDIT — re-run the converter to regenerate.

// ─── Bezier/curve helpers ────────────────────────────────────────────────────

function bezier3(p0: number, p1: number, p2: number, p3: number, t: number): number {
  const u = 1 - t; return u*u*u*p0 + 3*u*u*t*p1 + 3*u*t*t*p2 + t*t*t*p3;
}

interface PiecewiseCurve { start: number; end: number; p0: number; p1: number; p2: number; p3: number; }

function evalPiecewise(curves: PiecewiseCurve[], t: number): number {
  if (curves.length === 0) return 0;
  for (let i = 0; i < curves.length; i++) {
    const c = curves[i];
    if (t >= c.start && t <= c.end) {
      const nt = (c.end === c.start) ? 0 : (t - c.start) / (c.end - c.start);
      return bezier3(c.p0, c.p1, c.p2, c.p3, nt);
    }
  }
  if (t < curves[0].start) return bezier3(curves[0].p0, curves[0].p1, curves[0].p2, curves[0].p3, 0);
  const last = curves[curves.length - 1];
  return bezier3(last.p0, last.p1, last.p2, last.p3, 1.0);
}

interface ColorKey { value: { r: number; g: number; b: number }; pos: number; }
interface AlphaKey { value: number; pos: number; }

function evalAlpha(keys: AlphaKey[], t: number): number {
  for (let i = 0; i < keys.length - 1; i++) {
    if (t <= keys[i+1].pos) {
      const lt = (t - keys[i].pos) / (keys[i+1].pos - keys[i].pos);
      return keys[i].value + lt * (keys[i+1].value - keys[i].value);
    }
  }
  return keys[keys.length-1].value;
}

function evalColor(keys: ColorKey[], t: number) {
  for (let i = 0; i < keys.length - 1; i++) {
    if (t <= keys[i+1].pos) {
      const lt = (t - keys[i].pos) / (keys[i+1].pos - keys[i].pos);
      return {
        r: keys[i].value.r + lt * (keys[i+1].value.r - keys[i].value.r),
        g: keys[i].value.g + lt * (keys[i+1].value.g - keys[i].value.g),
        b: keys[i].value.b + lt * (keys[i+1].value.b - keys[i].value.b),
      };
    }
  }
  return keys[keys.length-1].value;
}

function rng(a: number, b: number) { return a + Math.random() * (b - a); }

// ─── VFX Class ───────────────────────────────────────────────────────────────

export class CartoonBlueGasExplosionNativeVFX {
  private scene: THREE.Scene;
  private camera: THREE.Camera;
  private activeFX: Array<{ update: (delta: number) => boolean }> = [];
  private tex0: THREE.Texture;
  private tex1: THREE.Texture;
  private tex2: THREE.Texture;
  private tex3: THREE.Texture;

  constructor(scene: THREE.Scene, camera: THREE.Camera) {
    this.scene = scene;
    this.camera = camera;
    const L = new THREE.TextureLoader();
    this.tex0 = L.load('/vfx/cartoon-blue-gas-explosion/tex_0.png');
    this.tex1 = L.load('/vfx/cartoon-blue-gas-explosion/tex_1.png');
    this.tex2 = L.load('/vfx/cartoon-blue-gas-explosion/tex_2.png');
    this.tex3 = L.load('/vfx/cartoon-blue-gas-explosion/tex_3.png');
  }

  public spawn(x: number, y: number, z: number) {
    const origin = new THREE.Vector3(x, y, z);
    const T = new THREE.Object3D();
    const hideM = new THREE.Matrix4().makeScale(0, 0, 0);
    const cq = this.camera.quaternion;
    const cfgColor = new THREE.Color(CHARACTER_CONFIG.skills.gasExplosion.hudColor);
    let age = 0;
    const cleanups: (() => void)[] = [];

    // ══════════════════════════════════════════════════════════
    // Emitter: SparksEmitter  (count=23, life=[0.25, 0.35], speed=[12, 28])
    // Texture: tex_0.png  Grid: 1x1
    // ══════════════════════════════════════════════════════════
    const cnt_SparksEmitter = 23;
    const geo_SparksEmitter = new THREE.PlaneGeometry(1, 1);
    const mat_SparksEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex0 }, speedFactor: { value: 0.0100 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor; attribute vec3 aVelocity; attribute vec3 aOffset;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        uniform float speedFactor;
        void main() {
          float c = mod(aFrame, 1.0); float r = floor(aFrame / 1.0);
          vUv = vec2((c + uv.x) / 1.0, 1.0 - (r + 1.0 - uv.y) / 1.0);
          vOpacity = aOpacity; vColor = aColor;
          vec4 mvPos = modelViewMatrix * vec4(aOffset, 1.0);
          vec3 viewVel = normalMatrix * aVelocity;
          float vlength = length(viewVel);
          float avgSize = (instanceMatrix[0][0] + instanceMatrix[1][1]) * 0.5;
          float sz = length(vec3(instanceMatrix[0][0], instanceMatrix[0][1], instanceMatrix[0][2]));
          mvPos.xyz += position.y * normalize(cross(mvPos.xyz, viewVel)) * sz;
          mvPos.xyz -= (position.x + 0.5) * viewVel * (1.0 + 1.0000 / max(vlength, 0.001)) * sz;
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * mvPos;
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.NormalBlending
    });
    const mesh_SparksEmitter = new THREE.InstancedMesh(geo_SparksEmitter, mat_SparksEmitter, cnt_SparksEmitter);
    mesh_SparksEmitter.frustumCulled = false;
    this.scene.add(mesh_SparksEmitter);
    const frm_SparksEmitter = new Float32Array(cnt_SparksEmitter);
    const opc_SparksEmitter = new Float32Array(cnt_SparksEmitter);
    const clr_SparksEmitter = new Float32Array(cnt_SparksEmitter * 3);
    mesh_SparksEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_SparksEmitter, 1));
    mesh_SparksEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_SparksEmitter, 1));
    mesh_SparksEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_SparksEmitter, 3));
    const vel_buf_SparksEmitter = new Float32Array(cnt_SparksEmitter * 3);
    const off_buf_SparksEmitter = new Float32Array(cnt_SparksEmitter * 3);
    mesh_SparksEmitter.geometry.setAttribute('aVelocity', new THREE.InstancedBufferAttribute(vel_buf_SparksEmitter, 3));
    mesh_SparksEmitter.geometry.setAttribute('aOffset', new THREE.InstancedBufferAttribute(off_buf_SparksEmitter, 3));

    const life_SparksEmitter: number[] = [];
    const maxLife_SparksEmitter: number[] = [];
    const pos_SparksEmitter: THREE.Vector3[] = [];
    const vel_SparksEmitter: THREE.Vector3[] = [];
    const sz_SparksEmitter: number[] = [];
    const rot_SparksEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_SparksEmitter; i++) {
      life_SparksEmitter.push(1.0);
      maxLife_SparksEmitter.push(1.0);
      pos_SparksEmitter.push(new THREE.Vector3(x, y, z));
      vel_SparksEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_SparksEmitter.push(0);
      rot_SparksEmitter.push(0);
      
    }

    let ptr_SparksEmitter = 0;
    let spawnTimer_SparksEmitter = 0;

    const spawnParticle_SparksEmitter = (i: number) => {
      life_SparksEmitter[i] = 0;
      maxLife_SparksEmitter[i] = rng(0.25, 0.35);
      sz_SparksEmitter[i] = rng(0.07, 0.07);
      rot_SparksEmitter[i] = rng(0, Math.PI * 2);
      
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(rng(-1, 1));
      const speed = rng(12, 28) * 2.0;
      const srad = 0.25 * 2.0;
      pos_SparksEmitter[i].set(
        x + Math.sin(phi) * Math.cos(theta) * srad,
        y + Math.sin(phi) * Math.sin(theta) * srad,
        z + Math.cos(phi) * srad
      );
      vel_SparksEmitter[i].set(
        Math.sin(phi) * Math.cos(theta) * speed,
        Math.sin(phi) * Math.sin(theta) * speed,
        Math.cos(phi) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_SparksEmitter = 13;
    for (let i = 0; i < Math.min(cnt_SparksEmitter, initialBurst_SparksEmitter); i++) {
      spawnParticle_SparksEmitter(ptr_SparksEmitter);
      ptr_SparksEmitter = (ptr_SparksEmitter + 1) % cnt_SparksEmitter;
    }
  
    const colorKeys_SparksEmitter: ColorKey[] | null = [{ value: { r: 1.00000, g: 1.00000, b: 1.00000 }, pos: 0.00000 }, { value: { r: 1.00000, g: 1.00000, b: 1.00000 }, pos: 1.00000 }];
    const alphaKeys_SparksEmitter: AlphaKey[] | null = [{ value: 0.00000, pos: 0.00000 }, { value: 1.00000, pos: 0.22353 }, { value: 1.00000, pos: 0.83487 }, { value: 0.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_SparksEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_SparksEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_SparksEmitter >= interval) {
          spawnParticle_SparksEmitter(ptr_SparksEmitter);
          ptr_SparksEmitter = (ptr_SparksEmitter + 1) % cnt_SparksEmitter;
          spawnTimer_SparksEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_SparksEmitter; i++) {
        if (life_SparksEmitter[i] >= maxLife_SparksEmitter[i]) {
          mesh_SparksEmitter.setMatrixAt(i, hideM);
          opc_SparksEmitter[i] = 0;
          continue;
        }
        life_SparksEmitter[i] += dt;
        const pct = Math.min(1, life_SparksEmitter[i] / maxLife_SparksEmitter[i]);
        if (life_SparksEmitter[i] >= maxLife_SparksEmitter[i]) {
          mesh_SparksEmitter.setMatrixAt(i, hideM);
          opc_SparksEmitter[i] = 0;
          continue;
        }
        // Physics: gravity + drag
        vel_SparksEmitter[i].y += -19.6 * dt;
        
        const speed_SparksEmitter = vel_SparksEmitter[i].length();
        const limit_SparksEmitter = 1 * 2.0;
        if (speed_SparksEmitter > limit_SparksEmitter) {
          const percent = (speed_SparksEmitter - limit_SparksEmitter) / speed_SparksEmitter;
          vel_SparksEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.2 * dt * 20));
        }
    
        pos_SparksEmitter[i].addScaledVector(vel_SparksEmitter[i], dt);
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0.6666666666666666, p3: 0}];
        const scaledSz = sz_SparksEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_SparksEmitter ? evalAlpha(alphaKeys_SparksEmitter, pct) : (1 - pct);
        const col = colorKeys_SparksEmitter ? evalColor(colorKeys_SparksEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        // StretchedBillboard: shader handles orientation via aVelocity/aOffset
        T.scale.setScalar(scaledSz);
        off_buf_SparksEmitter[i*3+0] = pos_SparksEmitter[i].x;
        off_buf_SparksEmitter[i*3+1] = pos_SparksEmitter[i].y;
        off_buf_SparksEmitter[i*3+2] = pos_SparksEmitter[i].z;
        vel_buf_SparksEmitter[i*3+0] = vel_SparksEmitter[i].x * 0.0100;
        vel_buf_SparksEmitter[i*3+1] = vel_SparksEmitter[i].y * 0.0100;
        vel_buf_SparksEmitter[i*3+2] = vel_SparksEmitter[i].z * 0.0100;
        
        T.updateMatrix();
        mesh_SparksEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [];
        const frameRaw = pct * 1;
        frm_SparksEmitter[i] = Math.min(0, Math.floor(frameRaw));
        opc_SparksEmitter[i] = alpha;
        clr_SparksEmitter[i*3+0] = col.r * cfgColor.r; clr_SparksEmitter[i*3+1] = col.g * cfgColor.g; clr_SparksEmitter[i*3+2] = col.b * cfgColor.b;
        mesh_SparksEmitter.geometry.attributes.aVelocity.needsUpdate = true;
        mesh_SparksEmitter.geometry.attributes.aOffset.needsUpdate = true;
      }
      mesh_SparksEmitter.instanceMatrix.needsUpdate = true;
      (mesh_SparksEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SparksEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SparksEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_SparksEmitter);
      geo_SparksEmitter.dispose(); mat_SparksEmitter.dispose();
      (mesh_SparksEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: GlowEmitter  (count=11, life=[0.3, 0.3], speed=[0, 0])
    // Texture: tex_1.png  Grid: 1x1
    // ══════════════════════════════════════════════════════════
    const cnt_GlowEmitter = 11;
    const geo_GlowEmitter = new THREE.PlaneGeometry(1, 1);
    const mat_GlowEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex1 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vUv = uv;
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_GlowEmitter = new THREE.InstancedMesh(geo_GlowEmitter, mat_GlowEmitter, cnt_GlowEmitter);
    mesh_GlowEmitter.frustumCulled = false;
    this.scene.add(mesh_GlowEmitter);
    const frm_GlowEmitter = new Float32Array(cnt_GlowEmitter);
    const opc_GlowEmitter = new Float32Array(cnt_GlowEmitter);
    const clr_GlowEmitter = new Float32Array(cnt_GlowEmitter * 3);
    mesh_GlowEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_GlowEmitter, 1));
    mesh_GlowEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_GlowEmitter, 1));
    mesh_GlowEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_GlowEmitter, 3));

    const life_GlowEmitter: number[] = [];
    const maxLife_GlowEmitter: number[] = [];
    const pos_GlowEmitter: THREE.Vector3[] = [];
    const vel_GlowEmitter: THREE.Vector3[] = [];
    const sz_GlowEmitter: number[] = [];
    const rot_GlowEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_GlowEmitter; i++) {
      life_GlowEmitter.push(1.0);
      maxLife_GlowEmitter.push(1.0);
      pos_GlowEmitter.push(new THREE.Vector3(x, y, z));
      vel_GlowEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_GlowEmitter.push(0);
      rot_GlowEmitter.push(0);
      
    }

    let ptr_GlowEmitter = 0;
    let spawnTimer_GlowEmitter = 0;

    const spawnParticle_GlowEmitter = (i: number) => {
      life_GlowEmitter[i] = 0;
      maxLife_GlowEmitter[i] = rng(0.3, 0.3);
      sz_GlowEmitter[i] = rng(5.75, 5.75);
      rot_GlowEmitter[i] = rng(0, Math.PI * 2);
      
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(rng(-1, 1));
      const speed = rng(0, 0) * 2.0;
      const srad = 0 * 2.0;
      pos_GlowEmitter[i].set(
        x + Math.sin(phi) * Math.cos(theta) * srad,
        y + Math.sin(phi) * Math.sin(theta) * srad,
        z + Math.cos(phi) * srad
      );
      vel_GlowEmitter[i].set(
        Math.sin(phi) * Math.cos(theta) * speed,
        Math.sin(phi) * Math.sin(theta) * speed,
        Math.cos(phi) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_GlowEmitter = 1;
    for (let i = 0; i < Math.min(cnt_GlowEmitter, initialBurst_GlowEmitter); i++) {
      spawnParticle_GlowEmitter(ptr_GlowEmitter);
      ptr_GlowEmitter = (ptr_GlowEmitter + 1) % cnt_GlowEmitter;
    }
  
    const colorKeys_GlowEmitter: ColorKey[] | null = [{ value: { r: 0.72941, g: 0.97647, b: 1.00000 }, pos: 0.00000 }, { value: { r: 0.00000, g: 1.00000, b: 1.00000 }, pos: 1.00000 }];
    const alphaKeys_GlowEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00000 }, { value: 0.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_GlowEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_GlowEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_GlowEmitter >= interval) {
          spawnParticle_GlowEmitter(ptr_GlowEmitter);
          ptr_GlowEmitter = (ptr_GlowEmitter + 1) % cnt_GlowEmitter;
          spawnTimer_GlowEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_GlowEmitter; i++) {
        if (life_GlowEmitter[i] >= maxLife_GlowEmitter[i]) {
          mesh_GlowEmitter.setMatrixAt(i, hideM);
          
          continue;
        }
        life_GlowEmitter[i] += dt;
        const pct = Math.min(1, life_GlowEmitter[i] / maxLife_GlowEmitter[i]);
        if (life_GlowEmitter[i] >= maxLife_GlowEmitter[i]) {
          mesh_GlowEmitter.setMatrixAt(i, hideM);
          
          continue;
        }
        // Physics: gravity + drag
        vel_GlowEmitter[i].y += 0 * dt;
        
        const speed_GlowEmitter = vel_GlowEmitter[i].length();
        const limit_GlowEmitter = 0.7 * 2.0;
        if (speed_GlowEmitter > limit_GlowEmitter) {
          const percent = (speed_GlowEmitter - limit_GlowEmitter) / speed_GlowEmitter;
          vel_GlowEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.09 * dt * 20));
        }
    
        pos_GlowEmitter[i].addScaledVector(vel_GlowEmitter[i], dt);
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0.89311555, p3: 0.61313975}];
        const scaledSz = sz_GlowEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_GlowEmitter ? evalAlpha(alphaKeys_GlowEmitter, pct) : (1 - pct);
        const col = colorKeys_GlowEmitter ? evalColor(colorKeys_GlowEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_GlowEmitter[i]);
        
        T.quaternion.copy(cq);
        T.rotateZ(rot_GlowEmitter[i]);
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_GlowEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [];
        const frameRaw = pct * 1;
        frm_GlowEmitter[i] = Math.min(0, Math.floor(frameRaw));
        opc_GlowEmitter[i] = alpha;
        clr_GlowEmitter[i*3+0] = col.r * cfgColor.r; clr_GlowEmitter[i*3+1] = col.g * cfgColor.g; clr_GlowEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_GlowEmitter.instanceMatrix.needsUpdate = true;
      (mesh_GlowEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_GlowEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_GlowEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_GlowEmitter);
      geo_GlowEmitter.dispose(); mat_GlowEmitter.dispose();
      (mesh_GlowEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: CloudBurstEmitter  (count=24, life=[0.6, 0.7], speed=[1, 8])
    // Texture: tex_2.png  Grid: 2x2
    // ══════════════════════════════════════════════════════════
    const cnt_CloudBurstEmitter = 24;
    const geo_CloudBurstEmitter = new THREE.PlaneGeometry(1, 1);
    const mat_CloudBurstEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex2 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          float c = mod(aFrame, 2.0); float r = floor(aFrame / 2.0);
          vUv = vec2((c + uv.x) / 2.0, 1.0 - (r + 1.0 - uv.y) / 2.0);
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_CloudBurstEmitter = new THREE.InstancedMesh(geo_CloudBurstEmitter, mat_CloudBurstEmitter, cnt_CloudBurstEmitter);
    mesh_CloudBurstEmitter.frustumCulled = false;
    this.scene.add(mesh_CloudBurstEmitter);
    const frm_CloudBurstEmitter = new Float32Array(cnt_CloudBurstEmitter);
    const opc_CloudBurstEmitter = new Float32Array(cnt_CloudBurstEmitter);
    const clr_CloudBurstEmitter = new Float32Array(cnt_CloudBurstEmitter * 3);
    mesh_CloudBurstEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_CloudBurstEmitter, 1));
    mesh_CloudBurstEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_CloudBurstEmitter, 1));
    mesh_CloudBurstEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_CloudBurstEmitter, 3));

    const life_CloudBurstEmitter: number[] = [];
    const maxLife_CloudBurstEmitter: number[] = [];
    const pos_CloudBurstEmitter: THREE.Vector3[] = [];
    const vel_CloudBurstEmitter: THREE.Vector3[] = [];
    const sz_CloudBurstEmitter: number[] = [];
    const rot_CloudBurstEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_CloudBurstEmitter; i++) {
      life_CloudBurstEmitter.push(1.0);
      maxLife_CloudBurstEmitter.push(1.0);
      pos_CloudBurstEmitter.push(new THREE.Vector3(x, y, z));
      vel_CloudBurstEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_CloudBurstEmitter.push(0);
      rot_CloudBurstEmitter.push(0);
      
    }

    let ptr_CloudBurstEmitter = 0;
    let spawnTimer_CloudBurstEmitter = 0;

    const spawnParticle_CloudBurstEmitter = (i: number) => {
      life_CloudBurstEmitter[i] = 0;
      maxLife_CloudBurstEmitter[i] = rng(0.6, 0.7);
      sz_CloudBurstEmitter[i] = rng(0.9, 1.2);
      rot_CloudBurstEmitter[i] = rng(0, Math.PI * 2);
      
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(rng(-1, 1));
      const speed = rng(1, 8) * 2.0;
      const srad = 0.2 * 2.0;
      pos_CloudBurstEmitter[i].set(
        x + Math.sin(phi) * Math.cos(theta) * srad,
        y + Math.sin(phi) * Math.sin(theta) * srad,
        z + Math.cos(phi) * srad
      );
      vel_CloudBurstEmitter[i].set(
        Math.sin(phi) * Math.cos(theta) * speed,
        Math.sin(phi) * Math.sin(theta) * speed,
        Math.cos(phi) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_CloudBurstEmitter = 14;
    for (let i = 0; i < Math.min(cnt_CloudBurstEmitter, initialBurst_CloudBurstEmitter); i++) {
      spawnParticle_CloudBurstEmitter(ptr_CloudBurstEmitter);
      ptr_CloudBurstEmitter = (ptr_CloudBurstEmitter + 1) % cnt_CloudBurstEmitter;
    }
  
    const colorKeys_CloudBurstEmitter: ColorKey[] | null = [{ value: { r: 0.00000, g: 0.37647, b: 0.56471 }, pos: 0.00000 }, { value: { r: 0.17647, g: 0.18039, b: 0.23529 }, pos: 1.00000 }];
    const alphaKeys_CloudBurstEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00000 }, { value: 1.00000, pos: 0.90001 }, { value: 0.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_CloudBurstEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_CloudBurstEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_CloudBurstEmitter >= interval) {
          spawnParticle_CloudBurstEmitter(ptr_CloudBurstEmitter);
          ptr_CloudBurstEmitter = (ptr_CloudBurstEmitter + 1) % cnt_CloudBurstEmitter;
          spawnTimer_CloudBurstEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_CloudBurstEmitter; i++) {
        if (life_CloudBurstEmitter[i] >= maxLife_CloudBurstEmitter[i]) {
          mesh_CloudBurstEmitter.setMatrixAt(i, hideM);
          opc_CloudBurstEmitter[i] = 0;
          continue;
        }
        life_CloudBurstEmitter[i] += dt;
        const pct = Math.min(1, life_CloudBurstEmitter[i] / maxLife_CloudBurstEmitter[i]);
        if (life_CloudBurstEmitter[i] >= maxLife_CloudBurstEmitter[i]) {
          mesh_CloudBurstEmitter.setMatrixAt(i, hideM);
          opc_CloudBurstEmitter[i] = 0;
          continue;
        }
        // Physics: gravity + drag
        vel_CloudBurstEmitter[i].y += 0 * dt;
        
        const speed_CloudBurstEmitter = vel_CloudBurstEmitter[i].length();
        const limit_CloudBurstEmitter = 0.5 * 2.0;
        if (speed_CloudBurstEmitter > limit_CloudBurstEmitter) {
          const percent = (speed_CloudBurstEmitter - limit_CloudBurstEmitter) / speed_CloudBurstEmitter;
          vel_CloudBurstEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.2 * dt * 20));
        }
    
        pos_CloudBurstEmitter[i].addScaledVector(vel_CloudBurstEmitter[i], dt);
        
        const rotSpeedBez_CloudBurstEmitter: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0, p3: 0}];
        rot_CloudBurstEmitter[i] += evalPiecewise(rotSpeedBez_CloudBurstEmitter, pct) * dt;
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0.6666666666666666, p3: 0}];
        const scaledSz = sz_CloudBurstEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_CloudBurstEmitter ? evalAlpha(alphaKeys_CloudBurstEmitter, pct) : (1 - pct);
        const col = colorKeys_CloudBurstEmitter ? evalColor(colorKeys_CloudBurstEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_CloudBurstEmitter[i]);
        
        T.quaternion.copy(cq);
        T.rotateZ(rot_CloudBurstEmitter[i]);
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_CloudBurstEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [{start: 0, end: 1.0, p0: 0, p1: 0, p2: 3.9996, p3: 3.9996}];
        const frameRaw = evalPiecewise(frameBez, pct);
        frm_CloudBurstEmitter[i] = Math.min(3, Math.floor(frameRaw));
        opc_CloudBurstEmitter[i] = alpha;
        clr_CloudBurstEmitter[i*3+0] = col.r * cfgColor.r; clr_CloudBurstEmitter[i*3+1] = col.g * cfgColor.g; clr_CloudBurstEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_CloudBurstEmitter.instanceMatrix.needsUpdate = true;
      (mesh_CloudBurstEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_CloudBurstEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_CloudBurstEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_CloudBurstEmitter);
      geo_CloudBurstEmitter.dispose(); mat_CloudBurstEmitter.dispose();
      (mesh_CloudBurstEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: TrailEmitter  (count=300, life=[0.25, 0.6], speed=[0, 0])
    // Texture: tex_2.png  Grid: 2x2
    // ══════════════════════════════════════════════════════════
    const cnt_TrailEmitter = 300;
    const geo_TrailEmitter = new THREE.PlaneGeometry(1, 1);
    const mat_TrailEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex2 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          float c = mod(aFrame, 2.0); float r = floor(aFrame / 2.0);
          vUv = vec2((c + uv.x) / 2.0, 1.0 - (r + 1.0 - uv.y) / 2.0);
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_TrailEmitter = new THREE.InstancedMesh(geo_TrailEmitter, mat_TrailEmitter, cnt_TrailEmitter);
    mesh_TrailEmitter.frustumCulled = false;
    this.scene.add(mesh_TrailEmitter);
    const frm_TrailEmitter = new Float32Array(cnt_TrailEmitter);
    const opc_TrailEmitter = new Float32Array(cnt_TrailEmitter);
    const clr_TrailEmitter = new Float32Array(cnt_TrailEmitter * 3);
    mesh_TrailEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_TrailEmitter, 1));
    mesh_TrailEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_TrailEmitter, 1));
    mesh_TrailEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_TrailEmitter, 3));

    const life_TrailEmitter: number[] = [];
    const maxLife_TrailEmitter: number[] = [];
    const pos_TrailEmitter: THREE.Vector3[] = [];
    const vel_TrailEmitter: THREE.Vector3[] = [];
    const sz_TrailEmitter: number[] = [];
    const rot_TrailEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_TrailEmitter; i++) {
      life_TrailEmitter.push(1.0);
      maxLife_TrailEmitter.push(1.0);
      pos_TrailEmitter.push(new THREE.Vector3(x, y, z));
      vel_TrailEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_TrailEmitter.push(0);
      rot_TrailEmitter.push(0);
      
    }

    let ptr_TrailEmitter = 0;
    let spawnTimer_TrailEmitter = 0;

    const spawnParticle_TrailEmitter = (i: number) => {
      life_TrailEmitter[i] = 0;
      maxLife_TrailEmitter[i] = rng(0.25, 0.6);
      sz_TrailEmitter[i] = rng(1, 0.56875);
      rot_TrailEmitter[i] = rng(0, Math.PI * 2);
      
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(rng(-1, 1));
      const speed = rng(0, 0) * 2.0;
      const srad = 0 * 2.0;
      pos_TrailEmitter[i].set(
        x + Math.sin(phi) * Math.cos(theta) * srad,
        y + Math.sin(phi) * Math.sin(theta) * srad,
        z + Math.cos(phi) * srad
      );
      vel_TrailEmitter[i].set(
        Math.sin(phi) * Math.cos(theta) * speed,
        Math.sin(phi) * Math.sin(theta) * speed,
        Math.cos(phi) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_TrailEmitter = 0;
    for (let i = 0; i < Math.min(cnt_TrailEmitter, initialBurst_TrailEmitter); i++) {
      spawnParticle_TrailEmitter(ptr_TrailEmitter);
      ptr_TrailEmitter = (ptr_TrailEmitter + 1) % cnt_TrailEmitter;
    }
  
    const colorKeys_TrailEmitter: ColorKey[] | null = [{ value: { r: 0.00000, g: 0.37647, b: 0.56471 }, pos: 0.00000 }, { value: { r: 0.17647, g: 0.18039, b: 0.23529 }, pos: 1.00000 }];
    const alphaKeys_TrailEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00000 }, { value: 1.00000, pos: 0.90001 }, { value: 0.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_TrailEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_TrailEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_TrailEmitter >= interval) {
          spawnParticle_TrailEmitter(ptr_TrailEmitter);
          ptr_TrailEmitter = (ptr_TrailEmitter + 1) % cnt_TrailEmitter;
          spawnTimer_TrailEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_TrailEmitter; i++) {
        if (life_TrailEmitter[i] >= maxLife_TrailEmitter[i]) {
          mesh_TrailEmitter.setMatrixAt(i, hideM);
          opc_TrailEmitter[i] = 0;
          continue;
        }
        life_TrailEmitter[i] += dt;
        const pct = Math.min(1, life_TrailEmitter[i] / maxLife_TrailEmitter[i]);
        if (life_TrailEmitter[i] >= maxLife_TrailEmitter[i]) {
          mesh_TrailEmitter.setMatrixAt(i, hideM);
          opc_TrailEmitter[i] = 0;
          continue;
        }
        // Physics: gravity + drag
        vel_TrailEmitter[i].y += 1.9600000000000002 * dt;
        
        const speed_TrailEmitter = vel_TrailEmitter[i].length();
        const limit_TrailEmitter = 0 * 2.0;
        if (speed_TrailEmitter > limit_TrailEmitter) {
          const percent = (speed_TrailEmitter - limit_TrailEmitter) / speed_TrailEmitter;
          vel_TrailEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.05 * dt * 20));
        }
    
        pos_TrailEmitter[i].addScaledVector(vel_TrailEmitter[i], dt);
        
        const rotSpeedBez_TrailEmitter: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0.4065934, p3: 0.4065934}];
        rot_TrailEmitter[i] += evalPiecewise(rotSpeedBez_TrailEmitter, pct) * dt;
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 0.21464643, p0: 0.27548078, p1: 0.27548078, p2: 0.7724670801145349, p3: 0.77080387}, {start: 0.21464643, end: 1, p0: 0.77080387, p1: 0.7647184764478682, p2: 0.6540969042768533, p3: 0}];
        const scaledSz = sz_TrailEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_TrailEmitter ? evalAlpha(alphaKeys_TrailEmitter, pct) : (1 - pct);
        const col = colorKeys_TrailEmitter ? evalColor(colorKeys_TrailEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_TrailEmitter[i]);
        
        T.quaternion.copy(cq);
        T.rotateZ(rot_TrailEmitter[i]);
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_TrailEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [{start: 0, end: 1.0, p0: 0, p1: 0, p2: 3.9996, p3: 3.9996}];
        const frameRaw = evalPiecewise(frameBez, pct);
        frm_TrailEmitter[i] = Math.min(3, Math.floor(frameRaw));
        opc_TrailEmitter[i] = alpha;
        clr_TrailEmitter[i*3+0] = col.r * cfgColor.r; clr_TrailEmitter[i*3+1] = col.g * cfgColor.g; clr_TrailEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_TrailEmitter.instanceMatrix.needsUpdate = true;
      (mesh_TrailEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_TrailEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_TrailEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_TrailEmitter);
      geo_TrailEmitter.dispose(); mat_TrailEmitter.dispose();
      (mesh_TrailEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: SmokeTrailEmitter  (count=17, life=[0.3, 0.55], speed=[25, 40])
    // Texture: tex_0.png  Grid: 1x1
    // ══════════════════════════════════════════════════════════
    const cnt_SmokeTrailEmitter = 17;
    const geo_SmokeTrailEmitter = new THREE.PlaneGeometry(1, 1);
    const mat_SmokeTrailEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex0 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vUv = uv;
          
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending
    });
    const mesh_SmokeTrailEmitter = new THREE.InstancedMesh(geo_SmokeTrailEmitter, mat_SmokeTrailEmitter, cnt_SmokeTrailEmitter);
    mesh_SmokeTrailEmitter.frustumCulled = false;
    this.scene.add(mesh_SmokeTrailEmitter);
    const frm_SmokeTrailEmitter = new Float32Array(cnt_SmokeTrailEmitter);
    const opc_SmokeTrailEmitter = new Float32Array(cnt_SmokeTrailEmitter);
    const clr_SmokeTrailEmitter = new Float32Array(cnt_SmokeTrailEmitter * 3);
    mesh_SmokeTrailEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_SmokeTrailEmitter, 1));
    mesh_SmokeTrailEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_SmokeTrailEmitter, 1));
    mesh_SmokeTrailEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_SmokeTrailEmitter, 3));

    const life_SmokeTrailEmitter: number[] = [];
    const maxLife_SmokeTrailEmitter: number[] = [];
    const pos_SmokeTrailEmitter: THREE.Vector3[] = [];
    const vel_SmokeTrailEmitter: THREE.Vector3[] = [];
    const sz_SmokeTrailEmitter: number[] = [];
    const rot_SmokeTrailEmitter: number[] = [];
    const accumulatedDist_SmokeTrailEmitter: number[] = [];

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_SmokeTrailEmitter; i++) {
      life_SmokeTrailEmitter.push(1.0);
      maxLife_SmokeTrailEmitter.push(1.0);
      pos_SmokeTrailEmitter.push(new THREE.Vector3(x, y, z));
      vel_SmokeTrailEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_SmokeTrailEmitter.push(0);
      rot_SmokeTrailEmitter.push(0);
      accumulatedDist_SmokeTrailEmitter.push(0);
    }

    let ptr_SmokeTrailEmitter = 0;
    let spawnTimer_SmokeTrailEmitter = 0;

    const spawnParticle_SmokeTrailEmitter = (i: number) => {
      life_SmokeTrailEmitter[i] = 0;
      maxLife_SmokeTrailEmitter[i] = rng(0.3, 0.55);
      sz_SmokeTrailEmitter[i] = rng(0.24, 0.27);
      rot_SmokeTrailEmitter[i] = rng(0, Math.PI * 2);
      accumulatedDist_SmokeTrailEmitter[i] = 0;
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(rng(-1, 1));
      const speed = rng(25, 40) * 2.0;
      const srad = 0.01 * 2.0;
      pos_SmokeTrailEmitter[i].set(
        x + Math.sin(phi) * Math.cos(theta) * srad,
        y + Math.sin(phi) * Math.sin(theta) * srad,
        z + Math.cos(phi) * srad
      );
      vel_SmokeTrailEmitter[i].set(
        Math.sin(phi) * Math.cos(theta) * speed,
        Math.sin(phi) * Math.sin(theta) * speed,
        Math.cos(phi) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_SmokeTrailEmitter = 7;
    for (let i = 0; i < Math.min(cnt_SmokeTrailEmitter, initialBurst_SmokeTrailEmitter); i++) {
      spawnParticle_SmokeTrailEmitter(ptr_SmokeTrailEmitter);
      ptr_SmokeTrailEmitter = (ptr_SmokeTrailEmitter + 1) % cnt_SmokeTrailEmitter;
    }
  
    const colorKeys_SmokeTrailEmitter: ColorKey[] | null = [{ value: { r: 1.00000, g: 1.00000, b: 1.00000 }, pos: 0.00000 }, { value: { r: 1.00000, g: 1.00000, b: 1.00000 }, pos: 1.00000 }];
    const alphaKeys_SmokeTrailEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00000 }, { value: 1.00000, pos: 0.81186 }, { value: 0.00000, pos: 1.00000 }];

    // Update closure captured for this emitter
    const update_SmokeTrailEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_SmokeTrailEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_SmokeTrailEmitter >= interval) {
          spawnParticle_SmokeTrailEmitter(ptr_SmokeTrailEmitter);
          ptr_SmokeTrailEmitter = (ptr_SmokeTrailEmitter + 1) % cnt_SmokeTrailEmitter;
          spawnTimer_SmokeTrailEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_SmokeTrailEmitter; i++) {
        if (life_SmokeTrailEmitter[i] >= maxLife_SmokeTrailEmitter[i]) {
          mesh_SmokeTrailEmitter.setMatrixAt(i, hideM);
          
          continue;
        }
        life_SmokeTrailEmitter[i] += dt;
        const pct = Math.min(1, life_SmokeTrailEmitter[i] / maxLife_SmokeTrailEmitter[i]);
        if (life_SmokeTrailEmitter[i] >= maxLife_SmokeTrailEmitter[i]) {
          mesh_SmokeTrailEmitter.setMatrixAt(i, hideM);
          
          continue;
        }
        // Physics: gravity + drag
        vel_SmokeTrailEmitter[i].y += -19.6 * dt;
        
        const speed_SmokeTrailEmitter = vel_SmokeTrailEmitter[i].length();
        const limit_SmokeTrailEmitter = 2 * 2.0;
        if (speed_SmokeTrailEmitter > limit_SmokeTrailEmitter) {
          const percent = (speed_SmokeTrailEmitter - limit_SmokeTrailEmitter) / speed_SmokeTrailEmitter;
          vel_SmokeTrailEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.25 * dt * 20));
        }
    
        pos_SmokeTrailEmitter[i].addScaledVector(vel_SmokeTrailEmitter[i], dt);
        
        const rotSpeedBez_SmokeTrailEmitter: PiecewiseCurve[] = [{start: 0, end: 1, p0: 1, p1: 1, p2: 0.4065934, p3: 0.4065934}];
        rot_SmokeTrailEmitter[i] += evalPiecewise(rotSpeedBez_SmokeTrailEmitter, pct) * dt;
        


        
        const distMoved_SmokeTrailEmitter = vel_SmokeTrailEmitter[i].length() * dt;
        accumulatedDist_SmokeTrailEmitter[i] += distMoved_SmokeTrailEmitter;
        const subDist_SmokeTrailEmitter = 5 > 0 ? (1.0 / 5) * 2.0 : 0;
        if (subDist_SmokeTrailEmitter > 0) {
          while (accumulatedDist_SmokeTrailEmitter[i] >= subDist_SmokeTrailEmitter) {
            spawnParticle_TrailEmitter(ptr_TrailEmitter);
            pos_TrailEmitter[ptr_TrailEmitter].copy(pos_SmokeTrailEmitter[i]);
            ptr_TrailEmitter = (ptr_TrailEmitter + 1) % cnt_TrailEmitter;
            accumulatedDist_SmokeTrailEmitter[i] -= subDist_SmokeTrailEmitter;
          }
        }
        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 1, p0: 0.7692308, p1: 0.7692308, p2: 0.7843341866666667, p3: 0.46901894}];
        const scaledSz = sz_SmokeTrailEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_SmokeTrailEmitter ? evalAlpha(alphaKeys_SmokeTrailEmitter, pct) : (1 - pct);
        const col = colorKeys_SmokeTrailEmitter ? evalColor(colorKeys_SmokeTrailEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        T.position.copy(pos_SmokeTrailEmitter[i]);
        
        T.quaternion.copy(cq);
        T.rotateZ(rot_SmokeTrailEmitter[i]);
        
        T.scale.setScalar(scaledSz);
        
        T.updateMatrix();
        mesh_SmokeTrailEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [];
        const frameRaw = pct * 1;
        frm_SmokeTrailEmitter[i] = Math.min(0, Math.floor(frameRaw));
        opc_SmokeTrailEmitter[i] = alpha;
        clr_SmokeTrailEmitter[i*3+0] = col.r * cfgColor.r; clr_SmokeTrailEmitter[i*3+1] = col.g * cfgColor.g; clr_SmokeTrailEmitter[i*3+2] = col.b * cfgColor.b;
      }
      mesh_SmokeTrailEmitter.instanceMatrix.needsUpdate = true;
      (mesh_SmokeTrailEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SmokeTrailEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_SmokeTrailEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_SmokeTrailEmitter);
      geo_SmokeTrailEmitter.dispose(); mat_SmokeTrailEmitter.dispose();
      (mesh_SmokeTrailEmitter as THREE.InstancedMesh).dispose();
    });

    // ══════════════════════════════════════════════════════════
    // Emitter: GasExplosionBlueEmitter  (count=14, life=[0.17, 0.3], speed=[0.1, 0.1])
    // Texture: tex_3.png  Grid: 3x3
    // ══════════════════════════════════════════════════════════
    const cnt_GasExplosionBlueEmitter = 14;
    const geo_GasExplosionBlueEmitter = new THREE.PlaneGeometry(1, 1);
    const mat_GasExplosionBlueEmitter = new THREE.ShaderMaterial({
      uniforms: { uMap: { value: this.tex3 }, speedFactor: { value: 1.0000 } },
      vertexShader: `
        attribute float aFrame; attribute float aOpacity; attribute vec3 aColor; attribute vec3 aVelocity; attribute vec3 aOffset;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        uniform float speedFactor;
        void main() {
          float c = mod(aFrame, 3.0); float r = floor(aFrame / 3.0);
          vUv = vec2((c + uv.x) / 3.0, 1.0 - (r + 1.0 - uv.y) / 3.0);
          vOpacity = aOpacity; vColor = aColor;
          vec4 mvPos = modelViewMatrix * vec4(aOffset, 1.0);
          vec3 viewVel = normalMatrix * aVelocity;
          float vlength = length(viewVel);
          float avgSize = (instanceMatrix[0][0] + instanceMatrix[1][1]) * 0.5;
          float sz = length(vec3(instanceMatrix[0][0], instanceMatrix[0][1], instanceMatrix[0][2]));
          mvPos.xyz += position.y * normalize(cross(mvPos.xyz, viewVel)) * sz;
          mvPos.xyz -= (position.x + 0.5) * viewVel * (1.0 + 2.5000 / max(vlength, 0.001)) * sz;
          vOpacity = aOpacity; vColor = aColor;
          gl_Position = projectionMatrix * mvPos;
        }
      `,
      fragmentShader: `
        uniform sampler2D uMap;
        varying vec2 vUv; varying float vOpacity; varying vec3 vColor;
        void main() {
          
          vec4 t = texture2D(uMap, vUv); if (t.a < 0.05) discard;
          gl_FragColor = vec4(t.rgb * vColor, t.a * vOpacity);
          
        }
      `,
      transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.NormalBlending
    });
    const mesh_GasExplosionBlueEmitter = new THREE.InstancedMesh(geo_GasExplosionBlueEmitter, mat_GasExplosionBlueEmitter, cnt_GasExplosionBlueEmitter);
    mesh_GasExplosionBlueEmitter.frustumCulled = false;
    this.scene.add(mesh_GasExplosionBlueEmitter);
    const frm_GasExplosionBlueEmitter = new Float32Array(cnt_GasExplosionBlueEmitter);
    const opc_GasExplosionBlueEmitter = new Float32Array(cnt_GasExplosionBlueEmitter);
    const clr_GasExplosionBlueEmitter = new Float32Array(cnt_GasExplosionBlueEmitter * 3);
    mesh_GasExplosionBlueEmitter.geometry.setAttribute('aFrame', new THREE.InstancedBufferAttribute(frm_GasExplosionBlueEmitter, 1));
    mesh_GasExplosionBlueEmitter.geometry.setAttribute('aOpacity', new THREE.InstancedBufferAttribute(opc_GasExplosionBlueEmitter, 1));
    mesh_GasExplosionBlueEmitter.geometry.setAttribute('aColor', new THREE.InstancedBufferAttribute(clr_GasExplosionBlueEmitter, 3));
    const vel_buf_GasExplosionBlueEmitter = new Float32Array(cnt_GasExplosionBlueEmitter * 3);
    const off_buf_GasExplosionBlueEmitter = new Float32Array(cnt_GasExplosionBlueEmitter * 3);
    mesh_GasExplosionBlueEmitter.geometry.setAttribute('aVelocity', new THREE.InstancedBufferAttribute(vel_buf_GasExplosionBlueEmitter, 3));
    mesh_GasExplosionBlueEmitter.geometry.setAttribute('aOffset', new THREE.InstancedBufferAttribute(off_buf_GasExplosionBlueEmitter, 3));

    const life_GasExplosionBlueEmitter: number[] = [];
    const maxLife_GasExplosionBlueEmitter: number[] = [];
    const pos_GasExplosionBlueEmitter: THREE.Vector3[] = [];
    const vel_GasExplosionBlueEmitter: THREE.Vector3[] = [];
    const sz_GasExplosionBlueEmitter: number[] = [];
    const rot_GasExplosionBlueEmitter: number[] = [];
    

    // Pre-initialize pool items as inactive (life = maxLife)
    for (let i = 0; i < cnt_GasExplosionBlueEmitter; i++) {
      life_GasExplosionBlueEmitter.push(1.0);
      maxLife_GasExplosionBlueEmitter.push(1.0);
      pos_GasExplosionBlueEmitter.push(new THREE.Vector3(x, y, z));
      vel_GasExplosionBlueEmitter.push(new THREE.Vector3(0, 0, 0));
      sz_GasExplosionBlueEmitter.push(0);
      rot_GasExplosionBlueEmitter.push(0);
      
    }

    let ptr_GasExplosionBlueEmitter = 0;
    let spawnTimer_GasExplosionBlueEmitter = 0;

    const spawnParticle_GasExplosionBlueEmitter = (i: number) => {
      life_GasExplosionBlueEmitter[i] = 0;
      maxLife_GasExplosionBlueEmitter[i] = rng(0.17, 0.3);
      sz_GasExplosionBlueEmitter[i] = rng(2.2, 2.3);
      rot_GasExplosionBlueEmitter[i] = rng(0, Math.PI * 2);
      
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(rng(-1, 1));
      const speed = rng(0.1, 0.1) * 2.0;
      const srad = 0.01 * 2.0;
      pos_GasExplosionBlueEmitter[i].set(
        x + Math.sin(phi) * Math.cos(theta) * srad,
        y + Math.sin(phi) * Math.sin(theta) * srad,
        z + Math.cos(phi) * srad
      );
      vel_GasExplosionBlueEmitter[i].set(
        Math.sin(phi) * Math.cos(theta) * speed,
        Math.sin(phi) * Math.sin(theta) * speed,
        Math.cos(phi) * speed
      );
    };

    // Trigger initial bursts
    const initialBurst_GasExplosionBlueEmitter = 4;
    for (let i = 0; i < Math.min(cnt_GasExplosionBlueEmitter, initialBurst_GasExplosionBlueEmitter); i++) {
      spawnParticle_GasExplosionBlueEmitter(ptr_GasExplosionBlueEmitter);
      ptr_GasExplosionBlueEmitter = (ptr_GasExplosionBlueEmitter + 1) % cnt_GasExplosionBlueEmitter;
    }
  
    const colorKeys_GasExplosionBlueEmitter: ColorKey[] | null = [{ value: { r: 1.00000, g: 1.00000, b: 1.00000 }, pos: 0.00000 }, { value: { r: 0.44314, g: 0.95294, b: 1.00000 }, pos: 1.00000 }];
    const alphaKeys_GasExplosionBlueEmitter: AlphaKey[] | null = [{ value: 1.00000, pos: 0.00000 }, { value: 1.00000, pos: 0.90001 }];

    // Update closure captured for this emitter
    const update_GasExplosionBlueEmitter = (dt: number) => {
      // Spawn particles continuously over time
      const rate = 0;
      if (rate > 0) {
        spawnTimer_GasExplosionBlueEmitter += dt;
        const interval = 1.0 / rate;
        while (spawnTimer_GasExplosionBlueEmitter >= interval) {
          spawnParticle_GasExplosionBlueEmitter(ptr_GasExplosionBlueEmitter);
          ptr_GasExplosionBlueEmitter = (ptr_GasExplosionBlueEmitter + 1) % cnt_GasExplosionBlueEmitter;
          spawnTimer_GasExplosionBlueEmitter -= interval;
        }
      }

      for (let i = 0; i < cnt_GasExplosionBlueEmitter; i++) {
        if (life_GasExplosionBlueEmitter[i] >= maxLife_GasExplosionBlueEmitter[i]) {
          mesh_GasExplosionBlueEmitter.setMatrixAt(i, hideM);
          opc_GasExplosionBlueEmitter[i] = 0;
          continue;
        }
        life_GasExplosionBlueEmitter[i] += dt;
        const pct = Math.min(1, life_GasExplosionBlueEmitter[i] / maxLife_GasExplosionBlueEmitter[i]);
        if (life_GasExplosionBlueEmitter[i] >= maxLife_GasExplosionBlueEmitter[i]) {
          mesh_GasExplosionBlueEmitter.setMatrixAt(i, hideM);
          opc_GasExplosionBlueEmitter[i] = 0;
          continue;
        }
        // Physics: gravity + drag
        vel_GasExplosionBlueEmitter[i].y += 0 * dt;
        
        const speed_GasExplosionBlueEmitter = vel_GasExplosionBlueEmitter[i].length();
        const limit_GasExplosionBlueEmitter = 0 * 2.0;
        if (speed_GasExplosionBlueEmitter > limit_GasExplosionBlueEmitter) {
          const percent = (speed_GasExplosionBlueEmitter - limit_GasExplosionBlueEmitter) / speed_GasExplosionBlueEmitter;
          vel_GasExplosionBlueEmitter[i].multiplyScalar(Math.max(0, 1 - percent * 0.09 * dt * 20));
        }
    
        pos_GasExplosionBlueEmitter[i].addScaledVector(vel_GasExplosionBlueEmitter[i], dt);
        


        

        const sizeBez: PiecewiseCurve[] = [{start: 0, end: 1, p0: 0.58750004, p1: 0.9525568066666666, p2: 1, p3: 1}];
        const scaledSz = sz_GasExplosionBlueEmitter[i] * 2.0 * evalPiecewise(sizeBez, pct);

        const alpha = alphaKeys_GasExplosionBlueEmitter ? evalAlpha(alphaKeys_GasExplosionBlueEmitter, pct) : (1 - pct);
        const col = colorKeys_GasExplosionBlueEmitter ? evalColor(colorKeys_GasExplosionBlueEmitter, pct) : { r: 1, g: 1, b: 1 };

        T.position.set(0, 0, 0);
        T.quaternion.set(0, 0, 0, 1);
        
        // StretchedBillboard: shader handles orientation via aVelocity/aOffset
        T.scale.setScalar(scaledSz);
        off_buf_GasExplosionBlueEmitter[i*3+0] = pos_GasExplosionBlueEmitter[i].x;
        off_buf_GasExplosionBlueEmitter[i*3+1] = pos_GasExplosionBlueEmitter[i].y;
        off_buf_GasExplosionBlueEmitter[i*3+2] = pos_GasExplosionBlueEmitter[i].z;
        vel_buf_GasExplosionBlueEmitter[i*3+0] = vel_GasExplosionBlueEmitter[i].x * 1.0000;
        vel_buf_GasExplosionBlueEmitter[i*3+1] = vel_GasExplosionBlueEmitter[i].y * 1.0000;
        vel_buf_GasExplosionBlueEmitter[i*3+2] = vel_GasExplosionBlueEmitter[i].z * 1.0000;
        
        T.updateMatrix();
        mesh_GasExplosionBlueEmitter.setMatrixAt(i, T.matrix);

        const frameBez: PiecewiseCurve[] = [{start: 0, end: 1, p0: 0, p1: 3, p2: 6.000000000000001, p3: 9}];
        const frameRaw = evalPiecewise(frameBez, pct);
        frm_GasExplosionBlueEmitter[i] = Math.min(8, Math.floor(frameRaw));
        opc_GasExplosionBlueEmitter[i] = alpha;
        clr_GasExplosionBlueEmitter[i*3+0] = col.r * cfgColor.r; clr_GasExplosionBlueEmitter[i*3+1] = col.g * cfgColor.g; clr_GasExplosionBlueEmitter[i*3+2] = col.b * cfgColor.b;
        mesh_GasExplosionBlueEmitter.geometry.attributes.aVelocity.needsUpdate = true;
        mesh_GasExplosionBlueEmitter.geometry.attributes.aOffset.needsUpdate = true;
      }
      mesh_GasExplosionBlueEmitter.instanceMatrix.needsUpdate = true;
      (mesh_GasExplosionBlueEmitter.geometry.getAttribute('aFrame') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_GasExplosionBlueEmitter.geometry.getAttribute('aOpacity') as THREE.InstancedBufferAttribute).needsUpdate = true;
      (mesh_GasExplosionBlueEmitter.geometry.getAttribute('aColor') as THREE.InstancedBufferAttribute).needsUpdate = true;
    };

    cleanups.push(() => {
      this.scene.remove(mesh_GasExplosionBlueEmitter);
      geo_GasExplosionBlueEmitter.dispose(); mat_GasExplosionBlueEmitter.dispose();
      (mesh_GasExplosionBlueEmitter as THREE.InstancedMesh).dispose();
    });

    // ── Main animation tick ───────────────────────────────────────
    this.activeFX.push({
      update: (dt: number) => {
        age += dt;
        if (age > 2) {
          cleanups.forEach(fn => fn());
          return false;
        }
        const cq = this.camera.quaternion;
        void cq;
        update_SparksEmitter(dt);
        update_GlowEmitter(dt);
        update_CloudBurstEmitter(dt);
        update_TrailEmitter(dt);
        update_SmokeTrailEmitter(dt);
        update_GasExplosionBlueEmitter(dt);
        return true;
      }
    });
  }

  public update(delta: number) {
    for (let i = this.activeFX.length - 1; i >= 0; i--) {
      if (!this.activeFX[i].update(delta)) this.activeFX.splice(i, 1);
    }
  }
}
